### ISSUE TITLE
Bug when scrapping series with decimal user rating in Kavita

### ISSUE THREAD

**Issue by blastman0** [Snd-R/komf#103]
Good afternoon, i just encountered a bug and didn't see it in issues so i'm reporting it here (first time i do this, so forgive me if i didnt respect some kind of convention )

there is ia Bug when trying to identify a series with a decimal user rating, for example 3.5 (shows as 70% in kavita)
here's what shows in the log :

16:12:02.221 [OkHttp http://localhost:5000/...] INFO com.microsoft.signalr.HubConnection -- HubConnection started.
com.squareup.moshi.JsonDataException: Expected an int but was 3.5 at path $[76].userRating
        at com.squareup.moshi.JsonUtf8Reader.nextInt(JsonUtf8Reader.java:965)
        at com.squareup.moshi.StandardJsonAdapters$7.fromJson(StandardJsonAdapters.java:196)
        at com.squareup.moshi.StandardJsonAdapters$7.fromJson(StandardJsonAdapters.java:193)
        at org.snd.mediaserver.kavita.model.KavitaSeriesJsonAdapter.fromJson(KavitaSeriesJsonAdapter.kt:101)
        at org.snd.mediaserver.kavita.model.KavitaSeriesJsonAdapter.fromJson(KavitaSeriesJsonAdapter.kt:23)
        at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:41)
        at com.squareup.moshi.CollectionJsonAdapter.fromJson(CollectionJsonAdapter.java:81)
        at com.squareup.moshi.CollectionJsonAdapter$2.fromJson(CollectionJsonAdapter.java:55)
        at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:41)
        at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:205)
        at com.squareup.moshi.JsonAdapter.fromJson(JsonAdapter.java:70)
        at org.snd.mediaserver.kavita.KavitaClient.getSeries-O4iFY_8(KavitaClient.kt:311)
        at org.snd.mediaserver.kavita.KavitaMediaServerClientAdapter.getSeries-lUCXapU(KavitaMediaServerClientAdapter.kt:42)
        at org.snd.mediaserver.MetadataService.matchLibraryMetadata-lUCXapU(MetadataService.kt:101)
        at org.snd.api.MetadataController.matchLibrary$lambda$9(MetadataController.kt:121)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1623)

**Comment by blastman0** [comment]
ps: in my case it was only one series, and when i removed the user rating it worked
