### ISSUE TITLE
Failed to identify series: Request failed with status code 500

### ISSUE THREAD

**Issue by B0PE** [Snd-R/komf#106]
Hi, I cant get komf to work with kavita.
I set it up via docker compose and user-script.
The script says that it is connected. If I change settings via user-script-interface the application.yml gets changed too.

Now if I try to fetch data for a manga I get an error in Kavita:

`Failed to identify series: Request failed with status code 500`

On the other end I get this error from the docker container:

`
17:32:36.489 [RxCachedThreadScheduler-1] ERROR org.snd.mediaserver.kavita.KavitaEventListener -- kotlin.Unit
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
	at java.base/sun.nio.ch.Net.pollConnectNow(Unknown Source)
	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(Unknown Source)
	at java.base/sun.nio.ch.NioSocketImpl.connect(Unknown Source)
	at java.base/java.net.SocksSocketImpl.connect(Unknown Source)
	at java.base/java.net.Socket.connect(Unknown Source)
	at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:128)
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:207)
	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.kt:221)
	at org.snd.common.http.LoggingInterceptor.intercept(LoggingInterceptor.kt:20)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at org.snd.common.http.UserAgentInterceptor.intercept(UserAgentInterceptor.kt:10)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
	at org.snd.common.http.HttpClient$execute$1.invoke(HttpClient.kt:27)
	at org.snd.common.http.HttpClient$execute$1.invoke(HttpClient.kt:26)
	at org.snd.common.http.HttpClient.rateLimited$lambda$0(HttpClient.kt:54)
	at io.github.resilience4j.ratelimiter.RateLimiter.lambda$decorateCheckedSupplier$3(RateLimiter.java:219)
	at io.github.resilience4j.retry.Retry.lambda$decorateCheckedSupplier$1(Retry.java:135)
	at org.snd.common.http.HttpClient.rateLimited(HttpClient.kt:56)
	at org.snd.common.http.HttpClient.execute(HttpClient.kt:26)
	at org.snd.mediaserver.kavita.KavitaAuthClient.authenticate(KavitaAuthClient.kt:31)
	at org.snd.mediaserver.kavita.KavitaTokenProvider.getFreshToken(KavitaTokenProvider.kt:48)
	at org.snd.mediaserver.kavita.KavitaTokenProvider.updateAndGetToken(KavitaTokenProvider.kt:40)
	at org.snd.mediaserver.kavita.KavitaTokenProvider.getToken(KavitaTokenProvider.kt:30)
	at org.snd.mediaserver.kavita.KavitaEventListener.start$lambda$0(KavitaEventListener.kt:55)
	at io.reactivex.rxjava3.internal.operators.single.SingleDefer.subscribeActual(SingleDefer.java:36)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4799)
	at com.microsoft.signalr.HubConnection.start(HubConnection.java:246)
	at org.snd.mediaserver.kavita.KavitaEventListener.start$lambda$2(KavitaEventListener.kt:65)
	at io.reactivex.rxjava3.internal.operators.completable.CompletableDefer.subscribeActual(CompletableDefer.java:36)
	at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2857)
	at io.reactivex.rxjava3.internal.operators.completable.CompletableToFlowable.subscribeActual(CompletableToFlowable.java:31)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15864)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15810)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableRetryPredicate$RetrySubscriber.subscribeNext(FlowableRetryPredicate.java:124)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableRetryPredicate.subscribeActual(FlowableRetryPredicate.java:42)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15864)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15810)
	at io.reactivex.rxjava3.internal.operators.completable.CompletableFromPublisher.subscribeActual(CompletableFromPublisher.java:32)
	at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2857)
	at io.reactivex.rxjava3.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.run(CompletableSubscribeOn.java:64)
	at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:644)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
`

I am using pi-hole in my network, but even if I dissable it I get the same error.
Komf and Kavita are in the same docker network.

**Comment by maniccomputer** [comment]
@B0PE was there a fix for this? I'm having the exact same issue.

**Comment by B0PE** [comment]
I had an error in the IP for Kavita in the komf docker-compose.yml.

**Comment by maniccomputer** [comment]
Hmmm... Doesn't seem to be my issue. I've tried multiple manga and same issue. 

Side note...when navigating to localhost:8085 is it supposed to be "Not Found"?

I've tried getting this up and running on both Docker Desktop for Windows on my local PC and an Unraid Docker container and have had 0 luck. This is as far as I've gotten where I can now see the pencil icon (on the PC install), whereas before I couldn't get anything but the "Not Found" screen.

**Comment by B0PE** [comment]
You cannot access komf directly via IP:8085. In my opinion, the best way is via the browser plugin.
Are both containers in the same network?
If you are on the kavita web interface, you should see a puzzle symbol in the top right corner. When you click on it, does it say "connected" under Connection?

**Comment by maniccomputer** [comment]
Yes, they are both on the same network...in both cases I created a network following the directions.

Yes, on the PC install I see a puzzle with a "connected" under Connection.

**Comment by B0PE** [comment]
Can you post the container log with the error you get when querying metadata?

**Comment by maniccomputer** [comment]
`2023-11-10 15:47:51 15:47:51.694 [JettyServerThreadPool-36] WARN io.javalin.Javalin -- Uncaught exception
2023-11-10 15:47:51 java.net.ConnectException: Failed to connect to localhost/127.0.0.1:5000
2023-11-10 15:47:51     at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:297)
2023-11-10 15:47:51     at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:207)
2023-11-10 15:47:51     at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
2023-11-10 15:47:51     at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
2023-11-10 15:47:51     at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
2023-11-10 15:47:51     at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
2023-11-10 15:47:51     at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
2023-11-10 15:47:51     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
2023-11-10 15:47:51     at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
2023-11-10 15:47:51     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
2023-11-10 15:47:51     at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
2023-11-10 15:47:51     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
2023-11-10 15:47:51     at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
2023-11-10 15:47:51     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
2023-11-10 15:47:51     at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.kt:221)
2023-11-10 15:47:51     at org.snd.common.http.LoggingInterceptor.intercept(LoggingInterceptor.kt:20)
2023-11-10 15:47:51     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
2023-11-10 15:47:51     at org.snd.common.http.UserAgentInterceptor.intercept(UserAgentInterceptor.kt:10)
2023-11-10 15:47:51     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
2023-11-10 15:47:51     at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
2023-11-10 15:47:51     at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
2023-11-10 15:47:51     at org.snd.common.http.HttpClient$execute$1.invoke(HttpClient.kt:27)
2023-11-10 15:47:51     at org.snd.common.http.HttpClient$execute$1.invoke(HttpClient.kt:26)
2023-11-10 15:47:51     at org.snd.common.http.HttpClient.rateLimited$lambda$0(HttpClient.kt:54)
2023-11-10 15:47:51     at io.github.resilience4j.ratelimiter.RateLimiter.lambda$decorateCheckedSupplier$3(RateLimiter.java:219)
2023-11-10 15:47:51     at io.github.resilience4j.retry.Retry.lambda$decorateCheckedSupplier$1(Retry.java:135)
2023-11-10 15:47:51     at org.snd.common.http.HttpClient.rateLimited(HttpClient.kt:56)
2023-11-10 15:47:51     at org.snd.common.http.HttpClient.execute(HttpClient.kt:26)
2023-11-10 15:47:51     at org.snd.mediaserver.kavita.KavitaAuthClient.authenticate(KavitaAuthClient.kt:31)
2023-11-10 15:47:51     at org.snd.mediaserver.kavita.KavitaTokenProvider.getFreshToken(KavitaTokenProvider.kt:48)
2023-11-10 15:47:51     at org.snd.mediaserver.kavita.KavitaTokenProvider.updateAndGetToken(KavitaTokenProvider.kt:40)
2023-11-10 15:47:51     at org.snd.mediaserver.kavita.KavitaTokenProvider.getToken(KavitaTokenProvider.kt:30)
2023-11-10 15:47:51     at org.snd.common.http.KavitaBearerAuthInterceptor.intercept(KavitaBearerAuthInterceptor.kt:11)
2023-11-10 15:47:51     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
2023-11-10 15:47:51     at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
2023-11-10 15:47:51     at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
2023-11-10 15:47:51     at org.snd.common.http.HttpClient$execute$1.invoke(HttpClient.kt:27)
2023-11-10 15:47:51     at org.snd.common.http.HttpClient$execute$1.invoke(HttpClient.kt:26)
2023-11-10 15:47:51     at org.snd.common.http.HttpClient.rateLimited$lambda$0(HttpClient.kt:54)
2023-11-10 15:47:51     at io.github.resilience4j.ratelimiter.RateLimiter.lambda$decorateCheckedSupplier$3(RateLimiter.java:219)
2023-11-10 15:47:51     at io.github.resilience4j.retry.Retry.lambda$decorateCheckedSupplier$1(Retry.java:135)
2023-11-10 15:47:51     at org.snd.common.http.HttpClient.rateLimited(HttpClient.kt:56)
2023-11-10 15:47:51     at org.snd.common.http.HttpClient.execute(HttpClient.kt:26)
2023-11-10 15:47:51     at org.snd.mediaserver.kavita.KavitaClient.getSeries-ZrvrQEk(KavitaClient.kt:46)
2023-11-10 15:47:51     at org.snd.mediaserver.kavita.KavitaMediaServerClientAdapter.getSeries-APDQdY8(KavitaMediaServerClientAdapter.kt:33)
2023-11-10 15:47:51     at org.snd.mediaserver.MetadataService.setSeriesMetadata-_O6TCEk(MetadataService.kt:67)
2023-11-10 15:47:51     at org.snd.api.MetadataController.identifySeries(MetadataController.kt:92)
2023-11-10 15:47:51     at org.snd.api.MetadataController.register$lambda$1$lambda$0$identifySeries(MetadataController.kt:44)
2023-11-10 15:47:51     at io.javalin.routing.HandlerEntry.handle(HandlerEntry.kt:19)
2023-11-10 15:47:51     at io.javalin.http.servlet.DefaultTasks.HTTP$lambda$8$lambda$6$lambda$5(DefaultTasks.kt:39)
2023-11-10 15:47:51     at io.javalin.http.servlet.JavalinServlet.handleTask(JavalinServlet.kt:88)
2023-11-10 15:47:51     at io.javalin.http.servlet.JavalinServlet.handleSync(JavalinServlet.kt:53)
2023-11-10 15:47:51     at io.javalin.http.servlet.JavalinServlet.service(JavalinServlet.kt:41)
2023-11-10 15:47:51     at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:587)
2023-11-10 15:47:51     at io.javalin.jetty.JavalinJettyServlet.service(JavalinJettyServlet.kt:58)
2023-11-10 15:47:51     at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:587)
2023-11-10 15:47:51     at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:764)
2023-11-10 15:47:51     at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:529)
2023-11-10 15:47:51     at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)
2023-11-10 15:47:51     at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1570)
2023-11-10 15:47:51     at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)
2023-11-10 15:47:51     at io.javalin.jetty.JettyServer$start$wsAndHttpHandler$1.doHandle(JettyServer.kt:61)
2023-11-10 15:47:51     at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176)
2023-11-10 15:47:51     at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:484)
2023-11-10 15:47:51     at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1543)
2023-11-10 15:47:51     at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174)
2023-11-10 15:47:51     at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1303)
2023-11-10 15:47:51     at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129)
2023-11-10 15:47:51     at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:173)
2023-11-10 15:47:51     at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
2023-11-10 15:47:51     at org.eclipse.jetty.server.Server.handle(Server.java:563)
2023-11-10 15:47:51     at org.eclipse.jetty.server.HttpChannel.lambda$handle$0(HttpChannel.java:505)
2023-11-10 15:47:51     at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:762)
2023-11-10 15:47:51     at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:497)
2023-11-10 15:47:51     at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:282)
2023-11-10 15:47:51     at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)
2023-11-10 15:47:51     at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
2023-11-10 15:47:51     at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
2023-11-10 15:47:51     at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:416)
2023-11-10 15:47:51     at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:385)
2023-11-10 15:47:51     at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:272)
2023-11-10 15:47:51     at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.lambda$new$0(AdaptiveExecutionStrategy.java:140)
2023-11-10 15:47:51     at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411)
2023-11-10 15:47:51     at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)
2023-11-10 15:47:51     at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)
2023-11-10 15:47:51     at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)
2023-11-10 15:47:51     at java.base/java.lang.Thread.run(Unknown Source)
2023-11-10 15:47:51 Caused by: java.net.ConnectException: Connection refused
2023-11-10 15:47:51     at java.base/sun.nio.ch.Net.pollConnect(Native Method)
2023-11-10 15:47:51     at java.base/sun.nio.ch.Net.pollConnectNow(Unknown Source)
2023-11-10 15:47:51     at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(Unknown Source)
2023-11-10 15:47:51     at java.base/sun.nio.ch.NioSocketImpl.connect(Unknown Source)
2023-11-10 15:47:51     at java.base/java.net.SocksSocketImpl.connect(Unknown Source)
2023-11-10 15:47:51     at java.base/java.net.Socket.connect(Unknown Source)
2023-11-10 15:47:51     at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:128)
2023-11-10 15:47:51     at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295)
2023-11-10 15:47:51     ... 86 common frames omitted`

**Comment by B0PE** [comment]
Have you tried to use the network IP of Kavita and not localhost.

**Comment by maniccomputer** [comment]
Sorry, I'm not sure what that is.

**Comment by B0PE** [comment]
Your PC on which the Docker containers are running has an IP via which it can be reached in your home network (cmd - ipconfig). You now use this with port 5000 as KOMF_KAVITA_BASE_URI in your komf docker-compose.yml. In my case, for example, this is: KOMF_KAVITA_BASE_URI=http://192.168.178.131:5000

**Comment by maniccomputer** [comment]
Figured it out just after I sent it. Changed the IP to the one showed on ipconfig. Same issue but slightly different error message:

`2023-11-10 16:20:21 16:20:21.151 [JettyServerThreadPool-34] WARN io.javalin.Javalin -- Uncaught exception
2023-11-10 16:20:21 org.snd.common.exceptions.HttpException$Unauthorized: response code: 401 url: http://192.168.0.192:5000/api/plugin/authenticate?apiKey=16707507-d05d-4696-b126-c3976ae14ffb&pluginName=Komf body: {"status":401,"message":"Unauthorized","details":"   at API.Controllers.PluginController.Authenticate(String apiKey, String pluginName) in /home/runner/work/Kavita/Kavita/API/Controllers/PluginController.cs:line 52\n   at lambda_method2265(Closure, Object)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.\u003CInvokeActionMethodAsync\u003Eg__Awaited|12_0(ControllerActionInvoker invoker, ValueTask\u00601 actionResultValueTask)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.\u003CInvokeNextActionFilterAsync\u003Eg__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State\u0026 next, Scope\u0026 scope, Object\u0026 state, Boolean\u0026 isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()\n--- End of stack trace from previous location ---\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.\u003CInvokeFilterPipelineAsync\u003Eg__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.\u003CInvokeAsync\u003Eg__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.\u003CInvokeAsync\u003Eg__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)\n   at Microsoft.AspNetCore.Routing.EndpointMiddleware.\u003CInvoke\u003Eg__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)\n   at API.Startup.\u003C\u003Ec.\u003C\u003CConfigure\u003Eb__4_5\u003Ed.MoveNext() in /home/runner/work/Kavita/Kavita/API/Startup.cs:line 361\n--- End of stack trace from previous location ---\n   at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)\n   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)\n   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)\n   at Microsoft.AspNetCore.ResponseCaching.ResponseCachingMiddleware.Invoke(HttpContext httpContext)\n   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)\n   at API.Middleware.SecurityEventMiddleware.InvokeAsync(HttpContext context) in /home/runner/work/Kavita/Kavita/API/Middleware/SecurityMiddleware.cs:line 68"}
2023-11-10 16:20:21     at org.snd.common.http.HttpClient.throwException(HttpClient.kt:68)
2023-11-10 16:20:21     at org.snd.common.http.HttpClient.access$throwException(HttpClient.kt:16)
2023-11-10 16:20:21     at org.snd.common.http.HttpClient$execute$1.invoke(HttpClient.kt:28)
2023-11-10 16:20:21     at org.snd.common.http.HttpClient$execute$1.invoke(HttpClient.kt:26)
2023-11-10 16:20:21     at org.snd.common.http.HttpClient.rateLimited$lambda$0(HttpClient.kt:54)
2023-11-10 16:20:21     at io.github.resilience4j.ratelimiter.RateLimiter.lambda$decorateCheckedSupplier$3(RateLimiter.java:219)
2023-11-10 16:20:21     at io.github.resilience4j.retry.Retry.lambda$decorateCheckedSupplier$1(Retry.java:135)
2023-11-10 16:20:21     at org.snd.common.http.HttpClient.rateLimited(HttpClient.kt:56)
2023-11-10 16:20:21     at org.snd.common.http.HttpClient.execute(HttpClient.kt:26)
2023-11-10 16:20:21     at org.snd.mediaserver.kavita.KavitaAuthClient.authenticate(KavitaAuthClient.kt:31)
2023-11-10 16:20:21     at org.snd.mediaserver.kavita.KavitaTokenProvider.getFreshToken(KavitaTokenProvider.kt:48)
2023-11-10 16:20:21     at org.snd.mediaserver.kavita.KavitaTokenProvider.updateAndGetToken(KavitaTokenProvider.kt:40)
2023-11-10 16:20:21     at org.snd.mediaserver.kavita.KavitaTokenProvider.getToken(KavitaTokenProvider.kt:30)
2023-11-10 16:20:21     at org.snd.common.http.KavitaBearerAuthInterceptor.intercept(KavitaBearerAuthInterceptor.kt:11)
2023-11-10 16:20:21     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
2023-11-10 16:20:21     at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
2023-11-10 16:20:21     at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
2023-11-10 16:20:21     at org.snd.common.http.HttpClient$execute$1.invoke(HttpClient.kt:27)
2023-11-10 16:20:21     at org.snd.common.http.HttpClient$execute$1.invoke(HttpClient.kt:26)
2023-11-10 16:20:21     at org.snd.common.http.HttpClient.rateLimited$lambda$0(HttpClient.kt:54)
2023-11-10 16:20:21     at io.github.resilience4j.ratelimiter.RateLimiter.lambda$decorateCheckedSupplier$3(RateLimiter.java:219)
2023-11-10 16:20:21     at io.github.resilience4j.retry.Retry.lambda$decorateCheckedSupplier$1(Retry.java:135)
2023-11-10 16:20:21     at org.snd.common.http.HttpClient.rateLimited(HttpClient.kt:56)
2023-11-10 16:20:21     at org.snd.common.http.HttpClient.execute(HttpClient.kt:26)
2023-11-10 16:20:21     at org.snd.mediaserver.kavita.KavitaClient.getSeries-ZrvrQEk(KavitaClient.kt:46)
2023-11-10 16:20:21     at org.snd.mediaserver.kavita.KavitaMediaServerClientAdapter.getSeries-APDQdY8(KavitaMediaServerClientAdapter.kt:33)
2023-11-10 16:20:21     at org.snd.mediaserver.MetadataService.setSeriesMetadata-_O6TCEk(MetadataService.kt:67)
2023-11-10 16:20:21     at org.snd.api.MetadataController.identifySeries(MetadataController.kt:92)
2023-11-10 16:20:21     at org.snd.api.MetadataController.register$lambda$1$lambda$0$identifySeries(MetadataController.kt:44)
2023-11-10 16:20:21     at io.javalin.routing.HandlerEntry.handle(HandlerEntry.kt:19)
2023-11-10 16:20:21     at io.javalin.http.servlet.DefaultTasks.HTTP$lambda$8$lambda$6$lambda$5(DefaultTasks.kt:39)
2023-11-10 16:20:21     at io.javalin.http.servlet.JavalinServlet.handleTask(JavalinServlet.kt:88)
2023-11-10 16:20:21     at io.javalin.http.servlet.JavalinServlet.handleSync(JavalinServlet.kt:53)
2023-11-10 16:20:21     at io.javalin.http.servlet.JavalinServlet.service(JavalinServlet.kt:41)
2023-11-10 16:20:21     at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:587)
2023-11-10 16:20:21     at io.javalin.jetty.JavalinJettyServlet.service(JavalinJettyServlet.kt:58)
2023-11-10 16:20:21     at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:587)
2023-11-10 16:20:21     at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:764)
2023-11-10 16:20:21     at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:529)
2023-11-10 16:20:21     at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)
2023-11-10 16:20:21     at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1570)
2023-11-10 16:20:21     at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)
2023-11-10 16:20:21     at io.javalin.jetty.JettyServer$start$wsAndHttpHandler$1.doHandle(JettyServer.kt:61)
2023-11-10 16:20:21     at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176)
2023-11-10 16:20:21     at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:484)
2023-11-10 16:20:21     at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1543)
2023-11-10 16:20:21     at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174)
2023-11-10 16:20:21     at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1303)
2023-11-10 16:20:21     at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129)
2023-11-10 16:20:21     at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:173)
2023-11-10 16:20:21     at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
2023-11-10 16:20:21     at org.eclipse.jetty.server.Server.handle(Server.java:563)
2023-11-10 16:20:21     at org.eclipse.jetty.server.HttpChannel.lambda$handle$0(HttpChannel.java:505)
2023-11-10 16:20:21     at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:762)
2023-11-10 16:20:21     at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:497)
2023-11-10 16:20:21     at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:282)
2023-11-10 16:20:21     at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)
2023-11-10 16:20:21     at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
2023-11-10 16:20:21     at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
2023-11-10 16:20:21     at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:416)
2023-11-10 16:20:21     at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:385)
2023-11-10 16:20:21     at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:272)
2023-11-10 16:20:21     at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.lambda$new$0(AdaptiveExecutionStrategy.java:140)
2023-11-10 16:20:21     at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411)
2023-11-10 16:20:21     at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)
2023-11-10 16:20:21     at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)
2023-11-10 16:20:21     at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)
2023-11-10 16:20:21     at java.base/java.lang.Thread.run(Unknown Source)
`

**Comment by B0PE** [comment]
Looks like the API key is incorrect. You should be careful not to accidentally make it public, as you did now. In other words, definitely change it now.

**Comment by maniccomputer** [comment]
SUCCESS!!!

Wow, I seriously cannot thank you enough!

Honestly, I think the issue was that I was using the API key from the sample code. Still, I redacted it above JIK.

**Comment by B0PE** [comment]
Glad I could help.
