### ISSUE TITLE
Requests failing 500 - Malformed JSON

### ISSUE THREAD

**Issue by Dgenner** [Snd-R/komf#108]
Kavita and Komf (both latest versions)  are both running on docker and are communicating well.  Setup was previously working, I believe this issue started with the most recent update.  I'll take some time this weekend and downgrade to see if the issue persists and report back. 

`11:38:49.357 [JettyServerThreadPool-49] WARN io.javalin.Javalin -- Uncaught exception
com.squareup.moshi.JsonEncodingException: Use JsonReader.setLenient(true) to accept malformed JSON at path $
    at com.squareup.moshi.JsonReader.syntaxError(JsonReader.java:243)
    at com.squareup.moshi.JsonUtf8Reader.checkLenient(JsonUtf8Reader.java:1154)
    at com.squareup.moshi.JsonUtf8Reader.doPeek(JsonUtf8Reader.java:386)
    at com.squareup.moshi.JsonUtf8Reader.peek(JsonUtf8Reader.java:208)
    at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:38)
    at com.squareup.moshi.JsonAdapter.fromJson(JsonAdapter.java:70)
    at org.snd.mediaserver.kavita.KavitaAuthClient.authenticate(KavitaAuthClient.kt:33)
    at org.snd.mediaserver.kavita.KavitaTokenProvider.getFreshToken(KavitaTokenProvider.kt:48)
    at org.snd.mediaserver.kavita.KavitaTokenProvider.updateAndGetToken(KavitaTokenProvider.kt:40)
    at org.snd.mediaserver.kavita.KavitaTokenProvider.getToken(KavitaTokenProvider.kt:30)
    at org.snd.common.http.KavitaBearerAuthInterceptor.intercept(KavitaBearerAuthInterceptor.kt:11)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
    at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
    at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
    at org.snd.common.http.HttpClient$execute$1.invoke(HttpClient.kt:27)
    at org.snd.common.http.HttpClient$execute$1.invoke(HttpClient.kt:26)
    at org.snd.common.http.HttpClient.rateLimited$lambda$0(HttpClient.kt:54)
    at io.github.resilience4j.ratelimiter.RateLimiter.lambda$decorateCheckedSupplier$3(RateLimiter.java:219)
    at io.github.resilience4j.retry.Retry.lambda$decorateCheckedSupplier$1(Retry.java:135)
    at org.snd.common.http.HttpClient.rateLimited(HttpClient.kt:56)
    at org.snd.common.http.HttpClient.execute(HttpClient.kt:26)
    at org.snd.mediaserver.kavita.KavitaClient.getSeries-ZrvrQEk(KavitaClient.kt:46)
    at org.snd.mediaserver.kavita.KavitaMediaServerClientAdapter.getSeries-APDQdY8(KavitaMediaServerClientAdapter.kt:33)
    at org.snd.mediaserver.MetadataService.setSeriesMetadata-_O6TCEk(MetadataService.kt:67)
    at org.snd.api.MetadataController.identifySeries(MetadataController.kt:92)
    at org.snd.api.MetadataController.register$lambda$1$lambda$0$identifySeries(MetadataController.kt:44)
    at io.javalin.routing.HandlerEntry.handle(HandlerEntry.kt:19)
    at io.javalin.http.servlet.DefaultTasks.HTTP$lambda$8$lambda$6$lambda$5(DefaultTasks.kt:39)
    at io.javalin.http.servlet.JavalinServlet.handleTask(JavalinServlet.kt:88)
    at io.javalin.http.servlet.JavalinServlet.handleSync(JavalinServlet.kt:53)
    at io.javalin.http.servlet.JavalinServlet.service(JavalinServlet.kt:41)
    at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:587)
    at io.javalin.jetty.JavalinJettyServlet.service(JavalinJettyServlet.kt:58)
    at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:587)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:764)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:529)
    at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1570)
    at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)
    at io.javalin.jetty.JettyServer$start$wsAndHttpHandler$1.doHandle(JettyServer.kt:61)
    at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:484)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1543)
    at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1303)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129)
    at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:173)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
    at org.eclipse.jetty.server.Server.handle(Server.java:563)
    at org.eclipse.jetty.server.HttpChannel.lambda$handle$0(HttpChannel.java:505)
    at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:762)
    at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:497)
    at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:282)
    at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)
    at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
    at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
    at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:416)
    at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:385)
    at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:272)
    at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.lambda$new$0(AdaptiveExecutionStrategy.java:140)
    at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)
    at java.base/java.lang.Thread.run(Unknown Source)
`

**Comment by Snd-R** [comment]
Not reproducible, no additional info was given, closing due to inactivity

**Comment by Pavelx9827** [comment]
I am also having this issue, is there any solition for it?
