### ISSUE TITLE
failed to restart the app 

### ISSUE THREAD

**Issue by Luca312** [Snd-R/komf#119]
kavita version 0.7.10.2
komf version 0.31.6

what i tried to run: java -jar komf-0.31.6.jar application.yml

error: 
[main] ERROR org.snd.Application -- Failed to start the app
java.nio.file.NoSuchFileException: C:\Users\Luca\Downloads\Kavita\kavita-win-x64.tar\Kavita\application.yml
        at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:96)
        at java.base/sun.nio.fs.WindowsLinkSupport.getRealPath(WindowsLinkSupport.java:288)
        at java.base/sun.nio.fs.WindowsPath.toRealPath(WindowsPath.java:947)
        at java.base/sun.nio.fs.WindowsPath.toRealPath(WindowsPath.java:42)
        at org.snd.config.ConfigLoader.loadFile(ConfigLoader.kt:20)
        at org.snd.module.context.AppContext.loadConfig(AppContext.kt:53)
        at org.snd.module.context.AppContext.refresh(AppContext.kt:36)
        at org.snd.module.context.AppContext.init(AppContext.kt:29)
        at org.snd.cli.Komf.run(Komf.kt:30)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:306)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:40)
        at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:458)
        at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:455)
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:475)
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:482)
        at org.snd.ApplicationKt.main(Application.kt:20)

**Comment by Snd-R** [comment]
make sure that you have correct path to application.yml in your run arguments
