### ISSUE TITLE
Support kavita 0.7.11 or higher version

### ISSUE THREAD

**Issue by sdepool** [Snd-R/komf#122]
Komf couldn't update metadata with kavita 0.7.11 or higher version

error:
19:55:02.890 [main] ERROR org.snd.Application -- Failed to start the app
com.squareup.moshi.JsonDataException: Required value 'writersLocked' missing at $
        at com.squareup.moshi.internal.Util.missingProperty(Util.java:660)
        at org.snd.mediaserver.kavita.model.KavitaSeriesMetadataJsonAdapter.fromJson(KavitaSeriesMetadataJsonAdapter.kt:240)
        at org.snd.mediaserver.kavita.model.KavitaSeriesMetadataJsonAdapter.fromJson(KavitaSeriesMetadataJsonAdapter.kt:25)
        at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:41)
        at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:205)
        at com.squareup.moshi.JsonAdapter.fromJson(JsonAdapter.java:70)
        at org.snd.mediaserver.kavita.KavitaClient.getSeriesMetadata-ZrvrQEk(KavitaClient.kt:317)
        at org.snd.mediaserver.kavita.KavitaMediaServerClientAdapter$getSeries$3.invoke(KavitaMediaServerClientAdapter.kt:48)
        at org.snd.mediaserver.kavita.KavitaMediaServerClientAdapter$getSeries$3.invoke(KavitaMediaServerClientAdapter.kt:47)
        at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
        at org.snd.mediaserver.MetadataService.matchLibraryMetadata-lUCXapU(MetadataService.kt:328)
        at org.snd.cli.Library$Update.run(Library.kt:21)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:306)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:319)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:319)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:40)
        at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:458)
        at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:455)
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:475)
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:482)
        at org.snd.ApplicationKt.main(Application.kt:20)

**Comment by ElryWeeb** [comment]
Please learn to read the erro message yourself before blindly saying "Support kavita 0.7.11 or higher version"
You clearly see an JsonDataException: Required value 'writersLocked' missing at $

**Comment by Snd-R** [comment]
fixed in https://github.com/Snd-R/komf/releases/tag/0.31.7

**Comment by ElryWeeb** [comment]
> fixed in https://github.com/Snd-R/komf/releases/tag/0.31.7

Weird i used it before with kavita 7.12 just fine
