### ISSUE TITLE
Unsupported file extension exception

### ISSUE THREAD

**Issue by ginocic** [Snd-R/komf#125]
when retrieving the metadata, Komf get all data and give them back to Komga but... I always get the same (strange?) "Uncaught exception" message for each series:

```code
11:19:04.847 [JettyServerThreadPool-28] WARN io.javalin.Javalin -- Uncaught exception
org.snd.common.exceptions.ValidationException: Unsupported file extension /data/Italiano/Mangaworld/Alya, Who Sits Next to Me, Sometimes Whispers Sweet Nothings in Russian/Oneshot [WindsOfManga].cbz
	at org.snd.metadata.epub.CalibreEpubMetadataWriter.validate(CalibreEpubMetadataWriter.kt:67)
	at org.snd.metadata.epub.CalibreEpubMetadataWriter.writeMetadata(CalibreEpubMetadataWriter.kt:50)
	at org.snd.metadata.epub.CalibreEpubMetadataWriter.writeMetadata(CalibreEpubMetadataWriter.kt:29)
	at org.snd.mediaserver.MetadataUpdateService.updateBookMetadata(MetadataUpdateService.kt:125)
	at org.snd.mediaserver.MetadataUpdateService.updateBookMetadata(MetadataUpdateService.kt:89)
	at org.snd.mediaserver.MetadataUpdateService.updateMetadata(MetadataUpdateService.kt:51)
	at org.snd.mediaserver.MetadataService.setSeriesMetadata-_O6TCEk(MetadataService.kt:86)
	at org.snd.api.MetadataController.identifySeries(MetadataController.kt:92)
	at org.snd.api.MetadataController.register$lambda$1$lambda$0$identifySeries(MetadataController.kt:44)
	at io.javalin.routing.HandlerEntry.handle(HandlerEntry.kt:19)
	at io.javalin.http.servlet.DefaultTasks.HTTP$lambda$8$lambda$6$lambda$5(DefaultTasks.kt:39)
	at io.javalin.http.servlet.JavalinServlet.handleTask(JavalinServlet.kt:88)
	at io.javalin.http.servlet.JavalinServlet.handleSync(JavalinServlet.kt:53)
	at io.javalin.http.servlet.JavalinServlet.service(JavalinServlet.kt:41)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:587)
	at io.javalin.jetty.JavalinJettyServlet.service(JavalinJettyServlet.kt:58)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:587)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:764)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:529)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1570)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)
	at io.javalin.jetty.JettyServer$start$wsAndHttpHandler$1.doHandle(JettyServer.kt:61)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:484)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1543)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1303)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129)
	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:173)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
	at org.eclipse.jetty.server.Server.handle(Server.java:563)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$0(HttpChannel.java:505)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:762)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:497)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:282)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:416)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:385)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:272)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.lambda$new$0(AdaptiveExecutionStrategy.java:140)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)
	at java.base/java.lang.Thread.run(Unknown Source)
```
I've tried to change the extension to cbr but then is an unsupported extension for Komga. 
Please, what can I do to get rid of this error message?

**Comment by Snd-R** [comment]
It tries to write metadata using opf write mode which is only supported for epubs. Disable OPF write mode in settings for that library
