### ISSUE TITLE
 Unhandled 503 Error in Komf Metadata Service

### ISSUE THREAD

**Issue by ShivamB25** [Snd-R/komf#127]
**Error Context:**
The Komf Metadata Service encountered an unhandled exception while searching for media information using the MAL (MyAnimeList) API. The error log provides details on the sequence of events leading to the issue:

1. At 10:06:50.122, the MetadataService initiated a search for "지금 우리 학교는" using MAL.
2. Matches were found at 10:06:50.356 (ANILIST) and 10:06:56.147 (MANGA_UPDATES).
3. At 10:07:11.870, an uncaught exception occurred in the JettyServerThreadPool-288, resulting in a 503 HTTP response code from the MAL API.

**Error Log:**
```plaintext
org.snd.common.exceptions.HttpException: response code: 503 url: https://api.myanimelist.net/v2/manga/139803?fields=id%2C%20title%2C%20main_picture%2C%20alternative_titles%2C%20start_date%2C%20end_date%2C%20synopsis%2C%20mean%2C%20rank%2C%20popularity%2C%20num_list_users%2C%20num_scoring_users%2C%20nsfw%2C%20genres%2C%20created_at%2C%20updated_at%2C%20media_type%2C%20status%2C%20num_volumes%2C%20num_chapters%2C%20authors%7Bfirst_name%2Clast_name%7D%2C%20pictures%2C%20background%2C%20serialization%7Bname%7D body: {}
   at org.snd.common.http.HttpClient.throwException(HttpClient.kt:69)
   ...
   at java.base/java.lang.Thread.run(Unknown Source)
```

**Steps to Reproduce:**
1. Trigger a search with the query "지금 우리 학교는" in the Komf Metadata Service.
2. Observe the service attempting to fetch data from the MAL API.
3. Analyze the response when accessing the MAL API endpoint "https://api.myanimelist.net/v2/manga/139803."

**Expected Behavior:**
The MetadataService should handle the 503 response from the MAL API gracefully, preventing uncaught exceptions and ensuring uninterrupted service.

**Possible Solutions:**
1. Implement proper error handling for HTTP 503 responses from the MAL API, providing a fallback mechanism or retry strategy.
2. Enhance logging to capture more details about the request and response when interacting with the MAL API for better diagnostics.

**Environment:**
- Komf Metadata Service version: latest as of 4 feb
- Operating System: Ubuntu 23.04 (podman)

**Comment by Snd-R** [comment]
MyAnimelist was having issue with their api. 
It is an intended behaviour to fail on unexpected error for a single series identification
If you want more details about request you can set application log level to DEBUG
