### ISSUE TITLE
missing 'id' value in the JSON response

### ISSUE THREAD

**Issue by ShivamB25** [Snd-R/komf#128]
### Error Description:
The `com.squareup.moshi.JsonDataException` is thrown due to a missing 'id' value in the JSON response. This issue occurs in the `MalClient.getSeries` method at line 83.

### Steps to Reproduce:
1. Trigger a search for "Inseng Jon Mang" using MANGA_UPDATES.
2. Trigger a search for "Loser Life" using MANGA_UPDATES.

### Observed Behavior:
The application crashes with a `JsonDataException` when processing the manga information from MANGA_UPDATES.

### Additional Details:
- Time of Occurrence: 08:47:40.427 (komf-meta-service-3)
- Thread: komf-event-listener-3
- ProviderSeriesId: id=30657361360

### Full Error Code:
```java
WARN io.javalin.Javalin -- Uncaught exception
org.snd.common.exceptions.HttpException: response code: 500 url: https://api.mangaupdates.com/v1/series/8879080689 body: {
    "status": "exception",
    "reason": "An unexpected exception occurred. Please report to an admin."
}
        at org.snd.common.http.HttpClient.throwException(HttpClient.kt:69)
        at org.snd.common.http.HttpClient.access$throwException(HttpClient.kt:16)
        at org.snd.common.http.HttpClient$execute$1.invoke(HttpClient.kt:28)
        at org.snd.common.http.HttpClient$execute$1.invoke(HttpClient.kt:26)
        at org.snd.common.http.HttpClient.rateLimited$lambda$0(HttpClient.kt:54)
        at io.github.resilience4j.ratelimiter.RateLimiter.lambda$decorateCheckedSupplier$3(RateLimiter.java:219)
        at io.github.resilience4j.retry.Retry.lambda$decorateCheckedSupplier$1(Retry.java:135)
        at org.snd.common.http.HttpClient.rateLimited(HttpClient.kt:56)
        at org.snd.common.http.HttpClient.execute(HttpClient.kt:26)
        at org.snd.metadata.providers.mangaupdates.MangaUpdatesClient.getSeries(MangaUpdatesClient.kt:55)
        at org.snd.metadata.providers.mangaupdates.MangaUpdatesMetadataProvider.matchSeriesMetadata(MangaUpdatesMetadataProvider.kt:78)
        at org.snd.mediaserver.MetadataService$matchSeries$4.invoke(MetadataService.kt:177)
        at org.snd.mediaserver.MetadataService$matchSeries$4.invoke(MetadataService.kt:177)
        at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
        at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:170)
        at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
        at kotlin.sequences.TransformingSequence$iterator$1.hasNext(Sequences.kt:214)
        at kotlin.sequences.SequencesKt___SequencesKt.firstOrNull(_Sequences.kt:168)
        at org.snd.mediaserver.MetadataService.matchSeries(MetadataService.kt:183)
        at org.snd.mediaserver.MetadataService.aggregateMetadataFromProviders$lambda$29$lambda$28(MetadataService.kt:261)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)

```

**Comment by papaj-na-wrotkach** [comment]
Yup, mangaupdates does not work for me too. It's interesting that you can normally open [the url](https://api.mangaupdates.com/v1/series/8879080689) in browser...

**Comment by ShivamB25** [comment]
😅

**Comment by Snd-R** [comment]
can't reproduce, might have been a temporary problem. Reopen if you still have this issue
