### ISSUE TITLE
JWT is not yet valid as the evaluation time

### ISSUE THREAD

**Issue by K0ng2** [Snd-R/komf#141]
```
03:32:24.189 [JettyServerThreadPool-27] WARN io.javalin.Javalin -- Uncaught exception
org.jose4j.jwt.consumer.InvalidJwtException: JWT (claims->{"name":"user","nameid":"1","role":["Admin","Login"],"nbf":1712349147,"exp":1713213147,"iat":1712349147}) rejected due to invalid claims or other invalid content. Additional details: [[6] The JWT is not yet valid as the evaluation time NumericDate{1712349144 -> Apr 6, 2024, 3:32:24 AM ICT} is before the Not Before (nbf=NumericDate{1712349147 -> Apr 6, 2024, 3:32:27 AM ICT}) claim time.]
        at org.jose4j.jwt.consumer.JwtConsumer.validate(JwtConsumer.java:459)
        at org.jose4j.jwt.consumer.JwtConsumer.processContext(JwtConsumer.java:304)
        at org.jose4j.jwt.consumer.JwtConsumer.process(JwtConsumer.java:410)
        at org.jose4j.jwt.consumer.JwtConsumer.processToClaims(JwtConsumer.java:171)
        at org.snd.mediaserver.kavita.KavitaTokenProvider.getFreshToken(KavitaTokenProvider.kt:49)
        at org.snd.mediaserver.kavita.KavitaTokenProvider.updateAndGetToken(KavitaTokenProvider.kt:40)
        at org.snd.mediaserver.kavita.KavitaTokenProvider.getToken(KavitaTokenProvider.kt:30)
        at org.snd.common.http.KavitaBearerAuthInterceptor.intercept(KavitaBearerAuthInterceptor.kt:11)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
        at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
        at org.snd.common.http.HttpClient$execute$1.invoke(HttpClient.kt:27)
        at org.snd.common.http.HttpClient$execute$1.invoke(HttpClient.kt:26)
        at org.snd.common.http.HttpClient.rateLimited$lambda$0(HttpClient.kt:54)
        at io.github.resilience4j.ratelimiter.RateLimiter.lambda$decorateCheckedSupplier$3(RateLimiter.java:219)
        at io.github.resilience4j.retry.Retry.lambda$decorateCheckedSupplier$1(Retry.java:135)
        at org.snd.common.http.HttpClient.rateLimited(HttpClient.kt:56)
        at org.snd.common.http.HttpClient.execute(HttpClient.kt:26)
        at org.snd.mediaserver.kavita.KavitaClient.getSeries-ZrvrQEk(KavitaClient.kt:46)
        at org.snd.mediaserver.kavita.KavitaMediaServerClientAdapter.getSeries-APDQdY8(KavitaMediaServerClientAdapter.kt:33)
        at org.snd.mediaserver.MetadataService.matchSeriesMetadata-APDQdY8(MetadataService.kt:114)
        at org.snd.api.MetadataController.matchLibrarySeries(MetadataController.kt:105)
        at org.snd.api.MetadataController.register$lambda$1$lambda$0$matchLibrarySeries(MetadataController.kt:46)
        at io.javalin.router.Endpoint.handle(Endpoint.kt:52)
        at io.javalin.router.ParsedEndpoint.handle(ParsedEndpoint.kt:15)
        at io.javalin.http.servlet.DefaultTasks.HTTP$lambda$9$lambda$7$lambda$6(DefaultTasks.kt:52)
        at io.javalin.http.servlet.JavalinServlet.handleTask(JavalinServlet.kt:99)
        at io.javalin.http.servlet.JavalinServlet.handleSync(JavalinServlet.kt:64)
        at io.javalin.http.servlet.JavalinServlet.handle(JavalinServlet.kt:50)
        at io.javalin.http.servlet.JavalinServlet.service(JavalinServlet.kt:30)
        at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:587)
        at io.javalin.jetty.JavalinJettyServlet.service(JavalinJettyServlet.kt:52)
        at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:587)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:764)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:529)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1580)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1381)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:484)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1553)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1303)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129)
        at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:173)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
        at org.eclipse.jetty.server.Server.handle(Server.java:563)
        at org.eclipse.jetty.server.HttpChannel$RequestDispatchable.dispatch(HttpChannel.java:1598)
        at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:753)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:501)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:287)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
        at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:421)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:390)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:277)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.produce(AdaptiveExecutionStrategy.java:193)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)
        at java.base/java.lang.Thread.run(Unknown Source)
```

work fine on Komga but error on Kavita

**Comment by Snd-R** [comment]
>The JWT is not yet valid as the evaluation time NumericDate{1712349144 -> Apr 6, 2024, 3:32:24 AM ICT} is before the Not Before (nbf=NumericDate{1712349147 -> Apr 6, 2024, 3:32:27 AM ICT}) claim time

Are you running Komf and Kavita on different machines? 
Kavita returns auth token and Komf then validates that token with local clock, and that clock seem to be 3 seconds ahead of Kavita

As a temporary workaround synchronizing clocks should work. This issue will be fixed in the next release
