### ISSUE TITLE
OPF mode not working

### ISSUE THREAD

**Issue by Roshri** [Snd-R/komf#147]
When trying to write metadata to an epub in opf mode, komf throws an exception and doesn't write anything to it. At first I thought it was related to switching my library type from Book to Light Novel in Kavita, but it's also happening on other libraries I haven't changed yet.

```java.io.IOException: Cannot run program "": CreateProcess error=87, The parameter is incorrect
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1140)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1074)
        at org.snd.metadata.epub.CalibreEpubMetadataWriter.writeMetadata(CalibreEpubMetadataWriter.kt:57)
        at org.snd.metadata.epub.CalibreEpubMetadataWriter.writeSeriesMetadata(CalibreEpubMetadataWriter.kt:46)
        at org.snd.mediaserver.MetadataUpdateService.updateBookMetadata(MetadataUpdateService.kt:124)
        at org.snd.mediaserver.MetadataUpdateService.updateBookMetadata(MetadataUpdateService.kt:89)
        at org.snd.mediaserver.MetadataUpdateService.updateMetadata(MetadataUpdateService.kt:51)
        at org.snd.mediaserver.MetadataService.setSeriesMetadata-_O6TCEk(MetadataService.kt:86)
        at org.snd.api.MetadataController.identifySeries(MetadataController.kt:92)
        at org.snd.api.MetadataController.register$lambda$1$lambda$0$identifySeries(MetadataController.kt:44)
        at io.javalin.router.Endpoint.handle(Endpoint.kt:52)
        at io.javalin.router.ParsedEndpoint.handle(ParsedEndpoint.kt:15)
        at io.javalin.http.servlet.DefaultTasks.HTTP$lambda$9$lambda$7$lambda$6(DefaultTasks.kt:52)
        at io.javalin.http.servlet.JavalinServlet.handleTask(JavalinServlet.kt:99)
        at io.javalin.http.servlet.JavalinServlet.handleSync(JavalinServlet.kt:64)
        at io.javalin.http.servlet.JavalinServlet.handle(JavalinServlet.kt:50)
        at io.javalin.http.servlet.JavalinServlet.service(JavalinServlet.kt:30)
        at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:587)
        at io.javalin.jetty.JavalinJettyServlet.service(JavalinJettyServlet.kt:52)
        at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:587)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:764)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:529)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1580)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1381)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:484)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1553)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1303)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129)
        at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:173)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
        at org.eclipse.jetty.server.Server.handle(Server.java:563)
        at org.eclipse.jetty.server.HttpChannel$RequestDispatchable.dispatch(HttpChannel.java:1598)
        at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:753)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:501)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:287)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
        at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:421)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:390)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:277)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.run(AdaptiveExecutionStrategy.java:199)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)
        at java.base/java.lang.Thread.run(Thread.java:1623)
Caused by: java.io.IOException: CreateProcess error=87, The parameter is incorrect
        at java.base/java.lang.ProcessImpl.create(Native Method)
        at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:500)
        at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:159)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1111)
        ... 50 common frames omitted```

**Comment by Roshri** [comment]
I don't know which one of these solved the issue
- Tried running komf from a new terminal
- Added Calibre's install directory to path
