### ISSUE TITLE
AccessDeniedException on .tmp Files when using COMICINFO

### ISSUE THREAD

**Issue by orc4n** [Snd-R/komf#158]
When using the HTTP endpoints (userscript), I keep running into errors with komf trying to access `.tmp` files.
It either always or never happens, depening on the manga series.

_Stack trace:_
```
23:50:26.903 [DefaultDispatcher-worker-1] ERROR snd.komf.mediaserver.metadata.MetadataService -- catching
java.nio.file.AccessDeniedException: /manga-directory/manga-name/1008308585286703136.tmp
        at java.base/sun.nio.fs.UnixException.translateToIOException(Unknown Source)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
        at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(Unknown Source)
        at java.base/java.nio.file.Files.newByteChannel(Unknown Source)
        at java.base/java.nio.file.Files.createFile(Unknown Source)
        at java.base/java.nio.file.TempFileHelper.create(Unknown Source)
        at java.base/java.nio.file.TempFileHelper.createTempFile(Unknown Source)
        at java.base/java.nio.file.Files.createTempFile(Unknown Source)
        at kotlin.io.path.PathsKt__PathUtilsKt.createTempFile(PathUtils.kt:943)
        at kotlin.io.path.PathsKt__PathUtilsKt.createTempFile$default(PathUtils.kt:941)
        at snd.komf.comicinfo.ComicInfoWriter.writeMetadata(ComicInfoWriter.kt:81)
        at snd.komf.mediaserver.metadata.MetadataUpdater.updateBookMetadata(MetadataUpdater.kt:124)
        at snd.komf.mediaserver.metadata.MetadataUpdater.access$updateBookMetadata(MetadataUpdater.kt:25)
        at snd.komf.mediaserver.metadata.MetadataUpdater$updateBookMetadata$3.invokeSuspend(MetadataUpdater.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:589)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:832)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:720)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:707)
```
_Versions:_
komf 1.0
Kavita Nightly 0.8.2.9
komf-userscript 0.12.1
Update method: COMICINFO (just API works fine)
Using docker, running on Proxmox priviliged LXC

**Comment by Snd-R** [comment]
Check if `manga-name` directory has write permissions

**Comment by orc4n** [comment]
All my directories have the same permissions: `drwxrwx--- 2 root root`
![image](https://github.com/user-attachments/assets/e527af6d-caae-476e-89f3-88b17bc6069b)
Komf is also running as using the root user.
I'm accessing the directories over an SMB share.
