### ISSUE TITLE
Komga and Konf - unable to apply metadata update/identify

### ISSUE THREAD

**Issue by jababda** [Snd-R/komf#183]
Hi all,

I'm able to login to Komga from Konf, but when I try to select a manga from the match list Konf errors.
This error happens on every manga I've tried and every match option I've tried.
I'm using docker desktop on windows with both komf and komga running in the same stack and network.

Error log:
```
2024-11-17 23:36:21 15:36:21.657 [DefaultDispatcher-worker-21] ERROR snd.komf.mediaserver.metadata.MetadataService -- catching
2024-11-17 23:36:21 java.net.ConnectException: Failed to connect to localhost/[0:0:0:0:0:0:0:1]:25600
2024-11-17 23:36:21     at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:297)
2024-11-17 23:36:21     at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:207)
2024-11-17 23:36:21     at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
2024-11-17 23:36:21     at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
2024-11-17 23:36:21     at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
2024-11-17 23:36:21     at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
2024-11-17 23:36:21     at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
2024-11-17 23:36:21     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
2024-11-17 23:36:21     at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
2024-11-17 23:36:21     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
2024-11-17 23:36:21     at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
2024-11-17 23:36:21     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
2024-11-17 23:36:21     at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
2024-11-17 23:36:21     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
2024-11-17 23:36:21     at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.kt:221)
2024-11-17 23:36:21     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
2024-11-17 23:36:21     at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
2024-11-17 23:36:21     at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
2024-11-17 23:36:21     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
2024-11-17 23:36:21     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
2024-11-17 23:36:21     at java.base/java.lang.Thread.run(Unknown Source)
2024-11-17 23:36:21     Suppressed: java.net.ConnectException: Failed to connect to localhost/127.0.0.1:25600
2024-11-17 23:36:21             ... 21 common frames omitted
2024-11-17 23:36:21     Caused by: java.net.ConnectException: Connection refused
2024-11-17 23:36:21             at java.base/sun.nio.ch.Net.pollConnect(Native Method)
2024-11-17 23:36:21             at java.base/sun.nio.ch.Net.pollConnectNow(Unknown Source)
2024-11-17 23:36:21             at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(Unknown Source)
2024-11-17 23:36:21             at java.base/sun.nio.ch.NioSocketImpl.connect(Unknown Source)
2024-11-17 23:36:21             at java.base/java.net.SocksSocketImpl.connect(Unknown Source)
2024-11-17 23:36:21             at java.base/java.net.Socket.connect(Unknown Source)
2024-11-17 23:36:21             at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:128)
2024-11-17 23:36:21             at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295)
2024-11-17 23:36:21             ... 20 common frames omitted
2024-11-17 23:36:21 Caused by: java.net.ConnectException: Connection refused
2024-11-17 23:36:21     at java.base/sun.nio.ch.Net.pollConnect(Native Method)
2024-11-17 23:36:21     at java.base/sun.nio.ch.Net.pollConnectNow(Unknown Source)
2024-11-17 23:36:21     at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(Unknown Source)
2024-11-17 23:36:21     at java.base/sun.nio.ch.NioSocketImpl.connect(Unknown Source)
2024-11-17 23:36:21     at java.base/java.net.SocksSocketImpl.connect(Unknown Source)
2024-11-17 23:36:21     at java.base/java.net.Socket.connect(Unknown Source)
2024-11-17 23:36:21     at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:128)
2024-11-17 23:36:21     at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295)
2024-11-17 23:36:21     ... 20 common frames omitted
```

docker-compose.yml
```yml
services:
  komga:
    image: gotson/komga:latest
    container_name: komga
    restart: unless-stopped
    user: "1000:1000"
    volumes:
      - ./Komga/config:/config
      - /mnt/j/Comics:/comics
    ports:
      - 25600:25600
    # remove the whole environment section if you don't need it
    environment:
      - TZ=Australia/Perth
  komf:
    image: sndxr/komf:latest
    container_name: komf
    restart: unless-stopped
    user: "1000:1000"
    environment:
      - KOMF_LOG_LEVEL=INFO
      # optional jvm options. Example config for low memory usage. Runs guaranteed cleanup up every 3600000ms(1hour)
      - JAVA_TOOL_OPTIONS=-XX:+UnlockExperimentalVMOptions -XX:+UseShenandoahGC -XX:ShenandoahGCHeuristics=compact -XX:ShenandoahGuaranteedGCInterval=3600000 -XX:TrimNativeHeapInterval=3600000
      - TZ=Australia/Perth
    volumes:
      - ./Komf/config:/config #path to directory with application.yml and database file
    ports:
      - "8085:8085"
```
Konfs application.yml
```yml
komga:
  komgaUser: "<myUsername>"
  komgaPassword: "<myPw>"
  eventListener:
    enabled: true
database:
  file: "/config/database.sqlite"
metadataProviders:
  defaultProviders:
    aniList:
      priority: 1
      enabled: true
```
Komga application.yml
```yaml
komga:
  cors.allowed-origins:
    - http://localhost:8085
```

**Comment by jababda** [comment]
The solution to this was adding the baseUri propert to the komga section of the konf application.yaml.
```yaml
komga:
  baseUri: "http://komga:25600"
  komgaUser: "<myUsername>"
  komgaPassword: "<myPw>"
  eventListener:
    enabled: true
database:
  file: "/config/database.sqlite"
metadataProviders:
  defaultProviders:
    aniList:
      priority: 1
      enabled: true
```
