### ISSUE TITLE
java.net.ConnectException: Failed to connect to localhost/127.0.0.1:80

### ISSUE THREAD

**Issue by lawrencejames24** [Snd-R/komf#185]
i have komf connected to komga thru user script but in the docker log im getting this error

09:57:27.557 [DefaultDispatcher-worker-5] WARN snd.komga.client.sse.OkHttpKomgaSseSession -- Event source error; response code null
java.net.ConnectException: Failed to connect to localhost/127.0.0.1:80
        at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:297)
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:207)
        at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
        at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
        at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
        at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.net.ConnectException: Connection refused
        at java.base/sun.nio.ch.Net.pollConnect(Native Method)
        at java.base/sun.nio.ch.Net.pollConnectNow(Unknown Source)
        at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(Unknown Source)
        at java.base/sun.nio.ch.NioSocketImpl.connect(Unknown Source)
        at java.base/java.net.SocksSocketImpl.connect(Unknown Source)
        at java.base/java.net.Socket.connect(Unknown Source)
        at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:128)
        at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295)
        ... 18 common frames omitted

**Comment by lawrencejames24** [comment]
ok made a little progress figured out it didnt have http:// in the uri but now i get this 
12:29:45.887 [OkHttp http://10.0.0.32/...] INFO http.logging -- --> GET http://10.0.0.32/api/v1/series?library_id=0HWDYZGMFQMZ8&size=500&page=0&unpaged=false
12:29:46.039 [OkHttp http://10.0.0.32/...] INFO http.logging -- <-- 302 Moved Temporarily http://10.0.0.32/api/v1/series?library_id=0HWDYZGMFQMZ8&size=500&page=0&unpaged=false (152ms, 138-byte body)
12:29:46.041 [OkHttp http://10.0.0.32/...] INFO http.logging -- --> GET http://10.0.0.32/login
12:29:46.109 [OkHttp http://10.0.0.32/...] INFO http.logging -- <-- 200 OK http://10.0.0.32/login (68ms, unknown-length body)
Exception in thread "DefaultDispatcher-worker-3" io.ktor.client.call.NoTransformationFoundException: Expected response body of the type 'class snd.komga.client.common.Page' but was 'class io.ktor.utils.io.SourceByteReadChannel'
In response from `http://10.0.0.32/login`
Response status `200 OK`
Response header `ContentType: text/html; charset=UTF-8` 
Request header `Accept: application/json`

You can read how to resolve NoTransformationFoundException at FAQ: 
https://ktor.io/docs/faq.html#no-transformation-found-exception
        at io.ktor.client.call.HttpClientCall.bodyNullable(HttpClientCall.kt:92)
        at snd.komga.client.series.HttpSeriesClient.getAllSeries(HttpSeriesClient.kt:226)
        at snd.komga.client.series.HttpSeriesClient$getAllSeries$1.invokeSuspend(HttpSeriesClient.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:589)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:832)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:720)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:707)
        Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@562685dc, Dispatchers.Default]
