### ISSUE TITLE
Failed to identify series: Request failed with status code 500

### ISSUE THREAD

**Issue by flamesky80** [Snd-R/komf#188]
Hi, I installed komf with docker and userscript, but can't get komf to work with kavita. 

here is pictures 
![000](https://github.com/user-attachments/assets/95fee2dc-11e7-4723-ad59-25485e72c037)
![001](https://github.com/user-attachments/assets/73da5fe9-a801-4108-b258-16902483ef99)
![002](https://github.com/user-attachments/assets/2d5fe822-230a-4fef-8601-01f8a691971b)
![003](https://github.com/user-attachments/assets/1db998ee-6404-4f20-ab3a-b96a862aa97d)
![004](https://github.com/user-attachments/assets/e6f46cde-636f-4027-b022-6d2f4c48be9a)
![005](https://github.com/user-attachments/assets/488ef672-443a-44ce-816c-eda98863b425)

and here is the error logs in docker:
`
17:12:07.838 [OkHttp https://api.bgm.tv/...] INFO http.logging -- --> POST https://api.bgm.tv/v0/search/subjects (90-byte body)
17:12:08.618 [OkHttp https://api.bgm.tv/...] INFO http.logging -- <-- 200 https://api.bgm.tv/v0/search/subjects (779ms, unknown-length body)
17:12:08.663 [DefaultDispatcher-worker-4] ERROR io.ktor.server.Application -- Unhandled: GET - /kavita/search
io.ktor.serialization.JsonConvertException: Illegal input: Fields [score, rank] are required for type with serial name 'snd.komf.providers.bangumi.model.SubjectSearchData', but they were missing at path: $.data[0]
        at io.ktor.serialization.kotlinx.KotlinxSerializationConverter.deserialize(KotlinxSerializationConverter.kt:77)
        at io.ktor.serialization.ContentConverterKt$deserialize$$inlined$map$1$2.emit(Emitters.kt:51)
        at kotlinx.coroutines.flow.FlowKt__BuildersKt$asFlow$$inlined$unsafeFlow$3.collect(SafeCollector.common.kt:111)
        at io.ktor.serialization.ContentConverterKt$deserialize$$inlined$map$1.collect(SafeCollector.common.kt:109)
        at kotlinx.coroutines.flow.FlowKt__ReduceKt.firstOrNull(Reduce.kt:239)
        at kotlinx.coroutines.flow.FlowKt.firstOrNull(Unknown Source)
        at io.ktor.serialization.ContentConverterKt.deserialize(ContentConverter.kt:97)
        at io.ktor.client.plugins.contentnegotiation.ContentNegotiationKt.ContentNegotiation$lambda$13$convertResponse(ContentNegotiation.kt:234)
        at io.ktor.client.plugins.contentnegotiation.ContentNegotiationKt.access$ContentNegotiation$lambda$13$convertResponse(ContentNegotiation.kt:1)
        at io.ktor.client.plugins.contentnegotiation.ContentNegotiationKt$ContentNegotiation$2$2.invokeSuspend(ContentNegotiation.kt:249)
        at io.ktor.client.plugins.contentnegotiation.ContentNegotiationKt$ContentNegotiation$2$2.invoke(ContentNegotiation.kt)
        at io.ktor.client.plugins.contentnegotiation.ContentNegotiationKt$ContentNegotiation$2$2.invoke(ContentNegotiation.kt)
        at io.ktor.client.plugins.api.TransformResponseBodyHook$install$1.invokeSuspend(KtorCallContexts.kt:104)
        at io.ktor.client.plugins.api.TransformResponseBodyHook$install$1.invoke(KtorCallContexts.kt)
        at io.ktor.client.plugins.api.TransformResponseBodyHook$install$1.invoke(KtorCallContexts.kt)
        at io.ktor.util.pipeline.DebugPipelineContext.proceedLoop(DebugPipelineContext.kt:79)
        at io.ktor.util.pipeline.DebugPipelineContext.proceed(DebugPipelineContext.kt:57)
        at io.ktor.client.HttpClient$4.invokeSuspend(HttpClient.kt:1315)
        at io.ktor.client.HttpClient$4.invoke(HttpClient.kt)
        at io.ktor.client.HttpClient$4.invoke(HttpClient.kt)
        at io.ktor.util.pipeline.DebugPipelineContext.proceedLoop(DebugPipelineContext.kt:79)
        at io.ktor.util.pipeline.DebugPipelineContext.proceed(DebugPipelineContext.kt:57)
        at io.ktor.client.plugins.ReceiveError$install$1.invokeSuspend(HttpCallValidator.kt:149)
        at io.ktor.client.plugins.ReceiveError$install$1.invoke(HttpCallValidator.kt)
        at io.ktor.client.plugins.ReceiveError$install$1.invoke(HttpCallValidator.kt)
        at io.ktor.util.pipeline.DebugPipelineContext.proceedLoop(DebugPipelineContext.kt:79)
        at io.ktor.util.pipeline.DebugPipelineContext.proceed(DebugPipelineContext.kt:57)
        at io.ktor.util.pipeline.DebugPipelineContext.execute$ktor_utils(DebugPipelineContext.kt:63)
        at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:86)
        at io.ktor.client.call.HttpClientCall.bodyNullable(HttpClientCall.kt:87)
        at snd.komf.providers.bangumi.BangumiClient.searchSeries(BangumiClient.kt:104)
        at snd.komf.providers.bangumi.BangumiClient$searchSeries$1.invokeSuspend(BangumiClient.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:589)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:832)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:720)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:707)
Caused by: kotlinx.serialization.MissingFieldException: Fields [score, rank] are required for type with serial name 'snd.komf.providers.bangumi.model.SubjectSearchData', but they were missing at path: $.data[0]
        at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:95)
        at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43)
        at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(AbstractDecoder.kt:70)
        at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableElement(StreamingJsonDecoder.kt:168)
        at kotlinx.serialization.encoding.CompositeDecoder$DefaultImpls.decodeSerializableElement$default(Decoding.kt:538)
        at kotlinx.serialization.internal.CollectionLikeSerializer.readElement(CollectionSerializers.kt:80)
        at kotlinx.serialization.internal.AbstractCollectionSerializer.readElement$default(CollectionSerializers.kt:51)
        at kotlinx.serialization.internal.AbstractCollectionSerializer.merge(CollectionSerializers.kt:36)
        at kotlinx.serialization.internal.AbstractCollectionSerializer.deserialize(CollectionSerializers.kt:43)
        at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:69)
        at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43)
        at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(AbstractDecoder.kt:70)
        at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableElement(StreamingJsonDecoder.kt:168)
        at snd.komf.providers.bangumi.model.SearchSubjectsResponse$$serializer.deserialize(SubjectSearch.kt:6)
        at snd.komf.providers.bangumi.model.SearchSubjectsResponse$$serializer.deserialize(SubjectSearch.kt:6)
        at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:69)
        at kotlinx.serialization.json.Json.decodeFromString(Json.kt:165)
        at io.ktor.serialization.kotlinx.KotlinxSerializationConverter.deserialize(KotlinxSerializationConverter.kt:69)
        ... 37 common frames omitted
Caused by: kotlinx.serialization.MissingFieldException: Fields [score, rank] are required for type with serial name 'snd.komf.providers.bangumi.model.SubjectSearchData', but they were missing
        at kotlinx.serialization.internal.PluginExceptionsKt.throwMissingFieldException(PluginExceptions.kt:20)
        at snd.komf.providers.bangumi.model.SubjectSearchData.<init>(SubjectSearch.kt:14)
        at snd.komf.providers.bangumi.model.SubjectSearchData$$serializer.deserialize(SubjectSearch.kt:14)
        at snd.komf.providers.bangumi.model.SubjectSearchData$$serializer.deserialize(SubjectSearch.kt:14)
        at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:69)
        ... 54 common frames omitted
17:13:41.243 [DefaultDispatcher-worker-2] INFO snd.komf.app.AppContext -- Reconfiguring application state
17:13:41.276 [DefaultDispatcher-worker-2] INFO snd.komf.mediaserver.kavita.KavitaEventHandler -- connecting to Kavita event listener http://192.xxx.xxx.xxx:xxx0/hubs/messages
17:13:41.283 [OkHttp http://192.xxx.xxx.xxx:xxx0/...] INFO com.microsoft.signalr.OkHttpWebSocketWrapper -- WebSocket closing with status code '1000' and reason ''.
17:13:41.289 [OkHttp http://192.xxx.xxx.xxx:xxx0/...] INFO com.microsoft.signalr.HubConnection -- HubConnection stopped.
17:13:41.290 [OkHttp http://192.xxx.xxx.xxx:xxx0/...] INFO com.microsoft.signalr.WebSocketTransport -- WebSocket connection stopped.
17:13:41.292 [OkHttp http://192.xxx.xxx.xxx:xxx0/...] INFO http.logging -- --> POST http://192.xxx.xxx.xxx:xxx0/api/plugin/authenticate?apiKey=3e9xxxxxxxxxxxxxx&pluginName=Komf (0-byte body)
17:13:41.318 [OkHttp http://192.xxx.xxx.xxx:xxx0/...] INFO http.logging -- <-- 200 OK http://192.xxx.xxx.xxx:xxx0/api/plugin/authenticate?apiKey=3e9xxxxxxxxxx&pluginName=Komf (26ms, unknown-length body)
17:13:41.347 [OkHttp http://192.xxx.xxx.xxx:xxx0/...] INFO com.microsoft.signalr.WebSocketTransport -- WebSocket transport connected to: ws://192.xxx.xxx.xxx:xxx0/hubs/messages?id=h9X9ctvFjO9AwY0SDIbI0w.
17:13:41.357 [OkHttp http://192.xxx.xxx.xxx:xxx0/...] INFO com.microsoft.signalr.HubConnection -- HubConnection started.
`

Can you help me, please?

**Comment by Kyuna0218** [comment]
我也是这样的，不知道为什么，是因为不支持bangumi了吗

**Comment by wangyeming** [comment]
Me too! Bangumi plugin seems not work!

**Comment by wangyeming** [comment]
@flamesky80 @Kyuna0218 可以加个联系方式吗？感觉对于komf的使用还有点疑问

**Comment by flamesky80** [comment]
> @flamesky80 @Kyuna0218 可以加个联系方式吗？感觉对于komf的使用还有点疑问

我也是新手，有啥问题可以提出来一起探讨。

**Comment by Kyuna0218** [comment]
刚看到，不好意思。我在那之后没用过了，nas性能不太够
________________________________
发件人: flamesky80 ***@***.***>
发送时间: 2024年12月6日 下午 03:25
收件人: Snd-R/komf ***@***.***>
抄送: Kyuna0218 ***@***.***>; Mention ***@***.***>
主题: Re: [Snd-R/komf] Failed to identify comic: Request failed with status code 500 (Issue #188)


@flamesky80<https://github.com/flamesky80> @Kyuna0218<https://github.com/Kyuna0218> 可以加个联系方式吗？感觉对于komf的使用还有点疑问

我也是新手，有啥问题可以提出来一起探讨。

―
