### ISSUE TITLE
application.yml causing errors in command prompt and on komga server

### ISSUE THREAD

**Issue by scottbrosnahan** [Snd-R/komf#32]
i just updated to the latest version of komf and komf userscript

it can now no longer run in  command line and if it does on my komga server it gives me errror code 500 when trying to match a manga

command prompt 
\Downloads>java -jar komf-0.17.1.jar C:\Users\scott\Downloads\application.yml.txt
18:44:00.720 [main] INFO io.javalin.Javalin - Starting Javalin ...
18:44:00.769 [main] ERROR io.javalin.Javalin - Failed to start Javalin
18:44:00.770 [main] INFO io.javalin.Javalin - Stopping Javalin ...
18:44:00.771 [main] ERROR io.javalin.Javalin - Javalin failed to stop gracefully
java.util.concurrent.ExecutionException: java.lang.IllegalStateException: STOPPED
        at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2096)
        at org.eclipse.jetty.server.Server.doStop(Server.java:490)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:132)
        at io.javalin.Javalin.stop(Javalin.java:207)
        at io.javalin.Javalin.start(Javalin.java:179)
        at io.javalin.Javalin.start(Javalin.java:148)
        at org.snd.module.ServerModule.<init>(ServerModule.kt:69)
        at org.snd.module.AppModule.<init>(AppModule.kt:40)
        at org.snd.module.AppContext.refresh(AppContext.kt:38)
        at org.snd.module.AppContext.init(AppContext.kt:28)
        at org.snd.cli.Komf.run(Komf.kt:30)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:198)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:18)
        at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:400)
        at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:397)
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:415)
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:440)
        at org.snd.ApplicationKt.main(Application.kt:18)
Caused by: java.lang.IllegalStateException: STOPPED
        at org.eclipse.jetty.server.handler.ContextHandler.shutdown(ContextHandler.java:773)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
        at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
        at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
        at org.eclipse.jetty.util.component.Graceful.shutdown(Graceful.java:146)
        ... 17 common frames omitted
18:44:00.773 [main] ERROR org.snd.Application - Failed to start the app
io.javalin.util.JavalinException: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: STOPPED
        at io.javalin.Javalin.stop(Javalin.java:211)
        at io.javalin.Javalin.start(Javalin.java:179)
        at io.javalin.Javalin.start(Javalin.java:148)
        at org.snd.module.ServerModule.<init>(ServerModule.kt:69)
        at org.snd.module.AppModule.<init>(AppModule.kt:40)
        at org.snd.module.AppContext.refresh(AppContext.kt:38)
        at org.snd.module.AppContext.init(AppContext.kt:28)
        at org.snd.cli.Komf.run(Komf.kt:30)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:198)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:18)
        at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:400)
        at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:397)
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:415)
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:440)
        at org.snd.ApplicationKt.main(Application.kt:18)
Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: STOPPED
        at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2096)
        at org.eclipse.jetty.server.Server.doStop(Server.java:490)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:132)
        at io.javalin.Javalin.stop(Javalin.java:207)
        ... 14 common frames omitted
Caused by: java.lang.IllegalStateException: STOPPED
        at org.eclipse.jetty.server.handler.ContextHandler.shutdown(ContextHandler.java:773)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
        at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
        at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
        at org.eclipse.jetty.util.component.Graceful.shutdown(Graceful.java:146)
        ... 17 common frames omitted

**Comment by Snd-R** [comment]
Looks like it doesn't properly report why server couldn't start up
Check that there's only one instance of komf running or that there's nothing else is using that port
