### ISSUE TITLE
[error] [error] [error]

### ISSUE THREAD

**Issue by edgehub-cloud** [Snd-R/komf#55]
11:46:29.375 [komf-event-listener-1] INFO org.snd.mediaserver.MetadataService -- searching "Platinum Blood" using MANGADEX
11:46:30.472 [komf-event-listener-1] INFO org.snd.mediaserver.MetadataService -- found match: "プラチナ・ブラッド" from MANGADEX  ProviderSeriesId(id=5249812c-9e9b-4797-a188-f9e5fd740ac0)
11:46:30.472 [komf-event-listener-1] INFO org.snd.mediaserver.MetadataService -- launching metadata aggregation using [MANGA_UPDATES, ANILIST, YEN_PRESS, KODANSHA, VIZ, BOOK_WALKER]
11:46:30.473 [komf-meta-service-3] INFO org.snd.mediaserver.MetadataService -- searching "プラチナ・ブラッド" using MANGA_UPDATES
11:46:30.473 [komf-meta-service-4] INFO org.snd.mediaserver.MetadataService -- searching "プラチナ・ブラッド" using YEN_PRESS
11:46:30.473 [komf-meta-service-2] INFO org.snd.mediaserver.MetadataService -- searching "プラチナ・ブラッド" using ANILIST
11:46:30.473 [komf-meta-service-1] INFO org.snd.mediaserver.MetadataService -- searching "プラチナ・ブラッド" using KODANSHA
11:46:30.942 [komf-meta-service-4] INFO org.snd.mediaserver.MetadataService -- searching "白金之血" using YEN_PRESS
11:46:31.011 [komf-meta-service-2] INFO org.snd.mediaserver.MetadataService -- searching "白金之血" using ANILIST
11:46:31.180 [komf-meta-service-4] INFO org.snd.mediaserver.MetadataService -- searching "プラチナ・ブラッド" using VIZ
11:46:31.264 [komf-meta-service-2] INFO org.snd.mediaserver.MetadataService -- searching "プラチナ・ブラッド" using BOOK_WALKER
11:46:31.506 [komf-meta-service-4] INFO org.snd.mediaserver.MetadataService -- searching "白金之血" using VIZ
11:46:31.723 [komf-meta-service-1] INFO org.snd.mediaserver.MetadataService -- searching "白金之血" using KODANSHA
11:46:32.093 [komf-meta-service-3] INFO org.snd.mediaserver.MetadataService -- found match: "Platinum Blood" from MANGA_UPDATES  ProviderSeriesId(id=9151322570)
11:46:35.959 [komf-meta-service-2] INFO org.snd.mediaserver.MetadataService -- searching "白金之血" using BOOK_WALKER
Exception in thread "komf-event-listener-1" java.lang.NullPointerException
        at org.snd.mediaserver.MetadataService.mergeMetadata(MetadataService.kt:279)
        at org.snd.mediaserver.MetadataService.aggregateMetadataFromProviders(MetadataService.kt:266)
        at org.snd.mediaserver.MetadataService.matchSeriesMetadata-APDQdY8(MetadataService.kt:135)
        at org.snd.mediaserver.komga.KomgaEventListener.processEvents(KomgaEventListener.kt:133)
        at org.snd.mediaserver.komga.KomgaEventListener.onEvent$lambda$6$lambda$5(KomgaEventListener.kt:119)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)

**Comment by edgehub-cloud** [comment]
```
11:52:38.896 [JettyServerThreadPool-108] INFO org.snd.mediaserver.MetadataService -- launching metadata aggregation using [MANGA_UPDATES, ANILIST, YEN_PRESS, KODANSHA, VIZ, BOOK_WALKER]
11:52:38.896 [komf-meta-service-3] INFO org.snd.mediaserver.MetadataService -- searching "プラチナ・ブラッド" using MANGA_UPDATES
11:52:38.896 [komf-meta-service-2] INFO org.snd.mediaserver.MetadataService -- searching "プラチナ・ブラッド" using KODANSHA
11:52:38.896 [komf-meta-service-4] INFO org.snd.mediaserver.MetadataService -- searching "プラチナ・ブラッド" using ANILIST
11:52:38.896 [komf-meta-service-1] INFO org.snd.mediaserver.MetadataService -- searching "プラチナ・ブラッド" using YEN_PRESS
11:52:39.389 [komf-meta-service-1] INFO org.snd.mediaserver.MetadataService -- searching "白金之血" using YEN_PRESS
11:52:39.599 [komf-meta-service-4] INFO org.snd.mediaserver.MetadataService -- searching "白金之血" using ANILIST
11:52:39.641 [komf-meta-service-1] INFO org.snd.mediaserver.MetadataService -- searching "プラチナ・ブラッド" using VIZ
11:52:39.652 [komf-meta-service-2] INFO org.snd.mediaserver.MetadataService -- searching "白金之血" using KODANSHA
11:52:39.776 [komf-meta-service-1] INFO org.snd.mediaserver.MetadataService -- searching "白金之血" using VIZ
11:52:39.836 [komf-meta-service-4] INFO org.snd.mediaserver.MetadataService -- searching "プラチナ・ブラッド" using BOOK_WALKER
11:52:40.577 [komf-meta-service-3] INFO org.snd.mediaserver.MetadataService -- found match: "Platinum Blood" from MANGA_UPDATES  ProviderSeriesId(id=9151322570)
11:52:41.013 [komf-meta-service-4] INFO org.snd.mediaserver.MetadataService -- searching "白金之血" using BOOK_WALKER
11:52:42.806 [JettyServerThreadPool-108] WARN io.javalin.Javalin -- Uncaught exception
java.lang.NullPointerException: null```

**Comment by edgehub-cloud** [comment]
some more new error
```11:55:03.952 [JettyServerThreadPool-121] INFO org.snd.mediaserver.MetadataService -- launching metadata aggregation using [MANGA_UPDATES, ANILIST, YEN_PRESS, KODANSHA, VIZ, BOOK_WALKER]
11:55:04.038 [komf-meta-service-4] INFO org.snd.mediaserver.MetadataService -- searching "Stan for Salvation" using ANILIST
11:55:04.308 [komf-meta-service-4] INFO org.snd.mediaserver.MetadataService -- searching "Saihate Shijuusou" using ANILIST
11:55:04.321 [JettyServerThreadPool-120] INFO org.snd.mediaserver.MetadataService -- (MANGADEX) fetching metadata for book 2
11:55:04.476 [komf-meta-service-2] INFO org.snd.mediaserver.MetadataService -- searching "サイハテ四重奏" using VIZ
11:55:04.570 [komf-meta-service-4] INFO org.snd.mediaserver.MetadataService -- searching "サイハテ四重奏" using BOOK_WALKER
11:55:04.596 [JettyServerThreadPool-115] INFO org.snd.mediaserver.MetadataUpdateService -- updating book Cheat Mode Farming in Another World c003 (2022) (Digital) (TooManyIsekai)
11:55:04.647 [komf-meta-service-1] INFO org.snd.mediaserver.MetadataService -- searching "Stan for Salvation" using KODANSHA
11:55:04.804 [komf-meta-service-2] INFO org.snd.mediaserver.MetadataService -- searching "Stan for Salvation" using VIZ
11:55:05.085 [komf-meta-service-3] INFO org.snd.mediaserver.MetadataService -- found match: "Saihate Quartet" from MANGA_UPDATES  ProviderSeriesId(id=53664275835)
11:55:05.086 [komf-meta-service-3] INFO org.snd.mediaserver.MetadataService -- searching "咲とファイナルファンタジーXIV" using MANGA_UPDATES
11:55:05.086 [JettyServerThreadPool-109] WARN io.javalin.Javalin -- Uncaught exception
com.squareup.moshi.JsonDataException: Required value 'image' missing at $.results[4]
        at com.squareup.moshi.internal.Util.missingProperty(Util.java:660)
        at org.snd.metadata.providers.yenpress.model.YenPressSearchResultJsonJsonAdapter.fromJson(YenPressSearchResultJsonJsonAdapter.kt:57)
        at org.snd.metadata.providers.yenpress.model.YenPressSearchResultJsonJsonAdapter.fromJson(YenPressSearchResultJsonJsonAdapter.kt:20)
        at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:41)
        at com.squareup.moshi.AdapterMethodsFactory$5.fromJson(AdapterMethodsFactory.java:295)
        at com.squareup.moshi.AdapterMethodsFactory$1.fromJson(AdapterMethodsFactory.java:97)
        at com.squareup.moshi.CollectionJsonAdapter.fromJson(CollectionJsonAdapter.java:81)
        at com.squareup.moshi.CollectionJsonAdapter$2.fromJson(CollectionJsonAdapter.java:55)
        at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:41)
        at org.snd.metadata.providers.yenpress.model.YenPressSearchResultsJsonAdapter.fromJson(YenPressSearchResultsJsonAdapter.kt:39)
        at org.snd.metadata.providers.yenpress.model.YenPressSearchResultsJsonAdapter.fromJson(YenPressSearchResultsJsonAdapter.kt:22)
        at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:41)
        at com.squareup.moshi.JsonAdapter.fromJson(JsonAdapter.java:70)
        at org.snd.metadata.providers.yenpress.YenPressClient.search(YenPressClient.kt:55)
        at org.snd.metadata.providers.yenpress.YenPressClient.searchSeries(YenPressClient.kt:36)
        at org.snd.metadata.providers.yenpress.YenPressMetadataProvider.matchSeriesMetadata(YenPressMetadataProvider.kt:59)
        at org.snd.mediaserver.MetadataService$matchSeries$4.invoke(MetadataService.kt:175)
        at org.snd.mediaserver.MetadataService$matchSeries$4.invoke(MetadataService.kt:175)
        at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
        at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:170)
        at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
        at kotlin.sequences.TransformingSequence$iterator$1.hasNext(Sequences.kt:214)
        at kotlin.sequences.SequencesKt___SequencesKt.firstOrNull(_Sequences.kt:168)
        at org.snd.mediaserver.MetadataService.matchSeries(MetadataService.kt:181)
        at org.snd.mediaserver.MetadataService.aggregateMetadataFromProviders$lambda$27$lambda$26(MetadataService.kt:256)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)

**Comment by ShivamB25** [comment]
22:21:04.614 [JettyServerThreadPool-985] INFO org.snd.mediaserver.MetadataService -- launching metadata aggregation using [MANGA_UPDATES, ANILIST, YEN_PRESS, KODANSHA, VIZ, BOOK_WALKER]
22:21:04.615 [komf-meta-service-3] INFO org.snd.mediaserver.MetadataService -- searching "押忍！！空手部" using MANGA_UPDATES
22:21:04.615 [komf-meta-service-1] INFO org.snd.mediaserver.MetadataService -- searching "押忍！！空手部" using ANILIST
22:21:04.615 [komf-meta-service-2] INFO org.snd.mediaserver.MetadataService -- searching "押忍！！空手部" using YEN_PRESS
22:21:04.615 [komf-meta-service-4] INFO org.snd.mediaserver.MetadataService -- searching "押忍！！空手部" using KODANSHA
22:21:04.947 [komf-meta-service-4] INFO org.snd.mediaserver.MetadataService -- searching "押忍！！空手部" using VIZ
22:21:04.956 [komf-meta-service-1] INFO org.snd.mediaserver.MetadataService -- searching "Osu!! Karate Bu" using ANILIST
22:21:05.039 [komf-meta-service-4] INFO org.snd.mediaserver.MetadataService -- searching "Osu!! Karate Bu" using VIZ
22:21:05.106 [komf-meta-service-2] INFO org.snd.mediaserver.MetadataService -- searching "Osu!! Karate Bu" using YEN_PRESS
22:21:05.165 [komf-meta-service-4] INFO org.snd.mediaserver.MetadataService -- searching "押忍！！空手部" using BOOK_WALKER
22:21:05.565 [komf-meta-service-4] INFO org.snd.mediaserver.MetadataService -- searching "Osu!! Karate Bu" using BOOK_WALKER
22:21:06.448 [komf-meta-service-3] INFO org.snd.mediaserver.MetadataService -- found match: "Osu!! Karatebu" from MANGA_UPDATES  ProviderSeriesId(id=17066145969)
22:21:06.448 [JettyServerThreadPool-985] WARN io.javalin.Javalin -- Uncaught exception
java.lang.NullPointerException: null
        at org.snd.metadata.providers.kodansha.KodanshaParser.parseSearchResults(KodanshaParser.kt:23)
        at org.snd.metadata.providers.kodansha.KodanshaClient.searchSeries(KodanshaClient.kt:31)
        at org.snd.metadata.providers.kodansha.KodanshaMetadataProvider.matchSeriesMetadata(KodanshaMetadataProvider.kt:52)
        at org.snd.mediaserver.MetadataService$matchSeries$4.invoke(MetadataService.kt:177)
        at org.snd.mediaserver.MetadataService$matchSeries$4.invoke(MetadataService.kt:177)
        at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
        at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:170)
        at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
        at kotlin.sequences.TransformingSequence$iterator$1.hasNext(Sequences.kt:214)
        at kotlin.sequences.SequencesKt___SequencesKt.firstOrNull(_Sequences.kt:168)
        at org.snd.mediaserver.MetadataService.matchSeries(MetadataService.kt:183)
        at org.snd.mediaserver.MetadataService.aggregateMetadataFromProviders$lambda$29$lambda$28(MetadataService.kt:261)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
