### ISSUE TITLE
[error] [error] 

### ISSUE THREAD

**Issue by ShivamB25** [Snd-R/komf#71]
5 [komf-meta-service-4] INFO org.snd.mediaserver.MetadataService -- found match: "Twin Star Exorcists" from VIZ  ProviderSeriesId(id=twin-star-exorcists-volume-1/product/3702)
14:00:37.855 [komf-meta-service-2] INFO org.snd.mediaserver.MetadataService -- searching "Экзорцисты Двух Звезд" using BOOK_WALKER
Exception in thread "komf-event-listener-2" java.util.concurrent.CompletionException: java.net.UnknownHostException: cdn.mangaupdates.com
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.net.UnknownHostException: cdn.mangaupdates.com
        at java.base/java.net.InetAddress$CachedAddresses.get(Unknown Source)
        at java.base/java.net.InetAddress.getAllByName0(Unknown Source)
        at java.base/java.net.InetAddress.getAllByName(Unknown Source)
        at java.base/java.net.InetAddress.getAllByName(Unknown Source)
        at okhttp3.Dns$Companion$DnsSystem.lookup(Dns.kt:49)
        at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.kt:164)
        at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.kt:129)
        at okhttp3.internal.connection.RouteSelector.next(RouteSelector.kt:71)
        at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:205)
        at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
        at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
        at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.kt:221)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
        at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
        at org.snd.common.http.HttpClient$executeWithByteResponse$1.invoke(HttpClient.kt:45)
        at org.snd.common.http.HttpClient$executeWithByteResponse$1.invoke(HttpClient.kt:44)
        at org.snd.common.http.HttpClient.rateLimited$lambda$0(HttpClient.kt:54)
        at io.github.resilience4j.ratelimiter.RateLimiter.lambda$decorateCheckedSupplier$3(RateLimiter.java:219)
        at io.github.resilience4j.retry.Retry.lambda$decorateCheckedSupplier$1(Retry.java:135)
        at org.snd.common.http.HttpClient.rateLimited(HttpClient.kt:56)
        at org.snd.common.http.HttpClient.executeWithByteResponse(HttpClient.kt:44)
        at org.snd.metadata.providers.mangaupdates.MangaUpdatesClient.getThumbnail(MangaUpdatesClient.kt:63)
        at org.snd.metadata.providers.mangaupdates.MangaUpdatesMetadataProvider.matchSeriesMetadata(MangaUpdatesMetadataProvider.kt:79)
        at org.snd.mediaserver.MetadataService$matchSeries$4.invoke(MetadataService.kt:177)
        at org.snd.mediaserver.MetadataService$matchSeries$4.invoke(MetadataService.kt:177)
        at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
        at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:170)
        at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
        at kotlin.sequences.TransformingSequence$iterator$1.hasNext(Sequences.kt:214)
        at kotlin.sequences.SequencesKt___SequencesKt.firstOrNull(_Sequences.kt:168)
        at org.snd.mediaserver.MetadataService.matchSeries(MetadataService.kt:183)
        at org.snd.mediaserver.MetadataService.aggregateMetadataFromProviders$lambda$29$lambda$28(MetadataService.kt:261)
        ... 4 more

**Comment by Snd-R** [comment]
It should be temporary error due to your internet being down for that moment or misconfigured dns service
Seems like Komf couldn't load this image https://cdn.mangaupdates.com/image/i415664.jpg

If it still not working then reopen this issue with more details
