### ISSUE TITLE
Viz cover image too big

### ISSUE THREAD

**Issue by rRoler** [Snd-R/komf#73]
Looks like the cover image for the [Bleach 20th Anniversary Edition on Viz](https://dw9to29mmj727.cloudfront.net/products/1974735982.png) is too big but Komf is still trying to upload it.

```
18:10:22.519 [JettyServerThreadPool-27] INFO org.snd.mediaserver.MetadataService -- attempting to match series "Bleach: 20th Anniversary Edition (Oneshot)" MediaServerSeriesId(id=[REDACTED])
18:10:22.519 [JettyServerThreadPool-27] INFO org.snd.mediaserver.MetadataService -- searching "Bleach: 20th Anniversary Edition (Oneshot)" using VIZ
18:10:26.796 [JettyServerThreadPool-27] INFO org.snd.mediaserver.MetadataService -- searching "Bleach: 20th Anniversary Edition" using VIZ
18:10:35.430 [JettyServerThreadPool-27] INFO org.snd.mediaserver.MetadataService -- found match: "Bleach 20th Anniversary Edition" from VIZ  ProviderSeriesId(id=bleach-volume-1/product/7136)
18:10:35.431 [JettyServerThreadPool-27] INFO org.snd.mediaserver.MetadataService -- launching metadata aggregation using [KODANSHA, YEN_PRESS, BOOK_WALKER, ANILIST, MANGA_UPDATES, MANGADEX]
18:10:35.431 [komf-meta-service-2] INFO org.snd.mediaserver.MetadataService -- searching "Bleach 20th Anniversary Edition" using KODANSHA
18:10:35.431 [komf-meta-service-3] INFO org.snd.mediaserver.MetadataService -- searching "Bleach 20th Anniversary Edition" using YEN_PRESS
18:10:35.431 [komf-meta-service-4] INFO org.snd.mediaserver.MetadataService -- searching "Bleach 20th Anniversary Edition" using BOOK_WALKER
18:10:35.431 [komf-meta-service-1] INFO org.snd.mediaserver.MetadataService -- searching "Bleach 20th Anniversary Edition" using ANILIST
18:10:39.785 [komf-meta-service-1] INFO org.snd.mediaserver.MetadataService -- searching "Bleach 20th Anniversary Edition" using MANGA_UPDATES
18:10:39.831 [komf-meta-service-3] INFO org.snd.mediaserver.MetadataService -- searching "Bleach 20th Anniversary Edition" using MANGADEX
18:10:44.632 [JettyServerThreadPool-27] INFO org.snd.mediaserver.MetadataUpdateService -- updating series bleach 20th anniversary edition (oneshot)
18:10:45.758 [JettyServerThreadPool-27] WARN io.javalin.Javalin -- Uncaught exception
org.snd.common.exceptions.HttpException: response code: 500 url: http://[REDACTED]/api/v1/series/[REDACTED]/thumbnails?selected=true body: {"timestamp":"2023-05-30T18:10:45.741+00:00","status":500,"error":"Internal Server Error","message":"Maximum upload size exceeded; nested exception is java.lang.IllegalStateException: org.apache.tomcat.util.http.fileupload.impl.FileSizeLimitExceededException: The field file exceeds its maximum permitted size of 1048576 bytes.","path":"/api/v1/series/[REDACTED]/thumbnails"}
	at org.snd.common.http.HttpClient.throwException(HttpClient.kt:69)
	at org.snd.common.http.HttpClient.access$throwException(HttpClient.kt:16)
	at org.snd.common.http.HttpClient$execute$1.invoke(HttpClient.kt:28)
	at org.snd.common.http.HttpClient$execute$1.invoke(HttpClient.kt:26)
	at org.snd.common.http.HttpClient.rateLimited$lambda$0(HttpClient.kt:54)
	at io.github.resilience4j.ratelimiter.RateLimiter.lambda$decorateCheckedSupplier$3(RateLimiter.java:219)
	at io.github.resilience4j.retry.Retry.lambda$decorateCheckedSupplier$1(Retry.java:135)
	at org.snd.common.http.HttpClient.rateLimited(HttpClient.kt:56)
	at org.snd.common.http.HttpClient.execute(HttpClient.kt:26)
	at org.snd.mediaserver.komga.KomgaClient.uploadSeriesThumbnail-w7W7Ha4(KomgaClient.kt:111)
	at org.snd.mediaserver.komga.KomgaMediaServerClientAdapter.uploadSeriesThumbnail-YU78aHo(KomgaMediaServerClientAdapter.kt:107)
	at org.snd.mediaserver.MetadataUpdateService.replaceSeriesThumbnail-uoHXl40(MetadataUpdateService.kt:169)
	at org.snd.mediaserver.MetadataUpdateService.updateSeriesMetadata(MetadataUpdateService.kt:68)
	at org.snd.mediaserver.MetadataUpdateService.updateMetadata(MetadataUpdateService.kt:47)
	at org.snd.mediaserver.MetadataService.matchSeriesMetadata-APDQdY8(MetadataService.kt:147)
	at org.snd.api.MetadataController.matchLibrarySeries(MetadataController.kt:105)
	at org.snd.api.MetadataController.register$lambda$1$lambda$0$matchLibrarySeries(MetadataController.kt:46)
	at io.javalin.routing.HandlerEntry.handle(HandlerEntry.kt:19)
	at io.javalin.http.servlet.DefaultTasks.HTTP$lambda-8$lambda-6$lambda-5(DefaultTasks.kt:38)
	at io.javalin.http.servlet.JavalinServlet.handleTask(JavalinServlet.kt:88)
	at io.javalin.http.servlet.JavalinServlet.handleSync(JavalinServlet.kt:53)
	at io.javalin.http.servlet.JavalinServlet.service(JavalinServlet.kt:41)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:587)
	at io.javalin.jetty.JavalinJettyServlet.service(JavalinJettyServlet.kt:58)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:587)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:764)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:529)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1570)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)
	at io.javalin.jetty.JettyServer$start$wsAndHttpHandler$1.doHandle(JettyServer.kt:57)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:484)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1543)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1304)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129)
	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:173)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
	at org.eclipse.jetty.server.Server.handle(Server.java:563)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$0(HttpChannel.java:505)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:762)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:497)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:282)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:416)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:385)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:272)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.produce(AdaptiveExecutionStrategy.java:194)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:936)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1080)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by Snd-R** [comment]
I don't think there's a way to get a smaller cover version other than converting it to smaller resolution or other format
The change to skip thumbnail upload if the size is too big was already added (https://github.com/Snd-R/komf/commit/78de848e330d9106854e7db1e97b0d0d60c38c38) but wasn't released yet 

I'll consider adding image conversion in the future but for now it will just skip cover upload if it's bigger that specified limit
