### ISSUE TITLE
NAS No write permission for file

### ISSUE THREAD

**Issue by Dgenner** [Snd-R/komf#92]
I'm not sure if this an issue or if it's some setup error on my part.  Komf seems to have no problem in API mode but when trying to write back to files on a mapped NAS drive it errors out.  Any clarity appreciated. 

```
org.snd.common.exceptions.ValidationException: No write permission for file Z:\Mapped\Network\Drive.cbz
        at org.snd.metadata.comicinfo.ComicInfoWriter.validate(ComicInfoWriter.kt:139)
        at org.snd.metadata.comicinfo.ComicInfoWriter.writeMetadata(ComicInfoWriter.kt:76)
        at org.snd.mediaserver.MetadataUpdateService.updateBookMetadata(MetadataUpdateService.kt:118)
        at org.snd.mediaserver.MetadataUpdateService.updateBookMetadata(MetadataUpdateService.kt:89)
        at org.snd.mediaserver.MetadataUpdateService.updateMetadata(MetadataUpdateService.kt:51)
        at org.snd.mediaserver.MetadataService.matchSeriesMetadata-APDQdY8(MetadataService.kt:147)
        at org.snd.api.MetadataController.matchLibrarySeries(MetadataController.kt:105)
        at org.snd.api.MetadataController.register$lambda$1$lambda$0$matchLibrarySeries(MetadataController.kt:46)
        at io.javalin.routing.HandlerEntry.handle(HandlerEntry.kt:19)
        at io.javalin.http.servlet.DefaultTasks.HTTP$lambda$8$lambda$6$lambda$5(DefaultTasks.kt:39)
        at io.javalin.http.servlet.JavalinServlet.handleTask(JavalinServlet.kt:88)
        at io.javalin.http.servlet.JavalinServlet.handleSync(JavalinServlet.kt:53)
        at io.javalin.http.servlet.JavalinServlet.service(JavalinServlet.kt:41)
        at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:587)
        at io.javalin.jetty.JavalinJettyServlet.service(JavalinJettyServlet.kt:58)
        at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:587)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:764)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:529)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1570)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)
        at io.javalin.jetty.JettyServer$start$wsAndHttpHandler$1.doHandle(JettyServer.kt:61)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:484)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1543)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1303)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129)
        at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:173)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
        at org.eclipse.jetty.server.Server.handle(Server.java:563)
        at org.eclipse.jetty.server.HttpChannel.lambda$handle$0(HttpChannel.java:505)
        at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:762)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:497)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:282)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
        at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)
        at java.base/java.lang.Thread.run(Thread.java:1623)
```

**Comment by Snd-R** [comment]
are you running komf  and komga/kavita on the same machine? Komf takes  filepath from komga/kavita and tries to access it the same way.
Make sure that the user that komf is running with have write permission to the files

**Comment by Dgenner** [comment]
Kavita and Komf are running on the same system, not running in docker.  They are communicating well as API update mode works fine.  Local files update as well.  The files are on a mapped NAS drive and the account it's using to access it has read/write permissions it has no issues reading the files at all.  Other tools running on the same server (ie. Flexget) aren't having issues writing to the remote share.  It's a headscratcher.

**Comment by Dgenner** [comment]
Not really a resolution but but a bit of a workaround to my issue.  The issue persists when running natively on my server, but when I have both Kavita and komf running in docker containers with CIFS volumes explicitly shared with both it's able to write tags.  I'm not sure running natively the NAS shares were mapped with admin privileges, but nothing I tried seemed to work.

**Comment by Kohega** [comment]
> are you running komf and komga/kavita on the same machine? Komf takes filepath from komga/kavita and tries to access it the same way.

I finally understood why it wasn't had permissions.
I DID NOT ADD THE LIBRARY AS "KOMF" VOLUME

After adding my manga location path to the komf docker container, no more writing issue.

**Comment by FelixLeChat** [comment]
@Kohega Can you show me with where/how dis you add your manga location path to the komf docker container ?

Thanks

**Comment by C3004** [comment]
@FelixLeChat
Simple Answer: Add the same -v mount to komf as you did to komga

**Comment by holocronweaver** [comment]
re: Docker containers not having dirs mounted, Komf should report this as 'file not found' rather than 'no write permission'. I think this is a bug in Komf error logging, leading to confusion since it implies a file permission problem when it is actually a file presence issue.
