### ISSUE TITLE
Komf spiking CPU usage for kavita - Possible rate limit issues

### ISSUE THREAD

**Issue by DieselTech** [Snd-R/komf#93]
Some of the API calls that are being sent are causing kavita to spike it's CPU usage. After the event listener fires off when a lot of new chapters are added in kavita, the CPU usage spikes to 400% (4 cores maxed out). 

> [Kavita] [2023-09-07 16:25:05.516 -04:00  227] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP POST /api/series/metadata responded 200 in 480206.2768 ms

This problem is compounded by the fact that on komf's end, I can't see the calls being made outbound. On kavita's side I can't see the inbound details of the API calls either, just that endpoints are being called. 

So this is like the perfect storm of not enough info from either party. I would love to help figure this out, but right now neither software has enough detail available to me in order to pinpoint it.  I *think* this has to do with how fast komf is calling the endpoints, with kavita's API not having enough time to work. I suspect kavita is returning `200 ok` right when it gets the call, not when the work itself is done. This is causing a large number of changes to attempt to get processed all at once. 

Maybe introducing a rate limit / wait time of 1 second between calls komf sends will help give kavita the processing time it needs to make changes. Even on my embedded J4125 CPU I still see most metadata endpoint calls complete in less than 200ms under normal circumstances.

**Comment by Snd-R** [comment]
Does is only happen when you update multiple series or also when you update just one series?
Do you use API or ComicInfo update mode?

I don't see what might be causing cpu usage on Kavita side, there are a few calls for db cleanup after metadata update to cleanup dangling references for genres, people etc. so if you have a lot of entries it might take a while to scan

The problem might also be because Kavita just added/updated series and is not finished processing it or is processing other  new series in parallel while komf already pushes updates which adds to the load

How does cpu load looks like when you just add series without komf?

**Comment by DieselTech** [comment]
The CPU spike happens even when updating a single series. This screenshot was having komf fetch the metadata for a series already in kavita (so no scanning / fighting for resources):

![image](https://github.com/Snd-R/komf/assets/30128380/996f5860-dd42-4492-8a12-ffcebadb9ab4)

It gets worse when the event listener is enabled and a bunch of new series are added, causing that level of CPU load for each new series at the same time. It usually ends up with me having to force kill the kavita container because it's gone unresponsive and is causing the system to hang.

**Comment by DieselTech** [comment]
Here's a crash from KOMF when triggering a scan in kavita:

```
00:15:25.263 [komf-event-listener-4] INFO org.snd.mediaserver.MetadataUpdateService -- updating series Chained Soldier
Exception in thread "komf-event-listener-4" java.net.SocketTimeoutException: timeout
	at okio.SocketAsyncTimeout.newTimeoutException(JvmOkio.kt:147)
	at okio.AsyncTimeout.access$newTimeoutException(AsyncTimeout.kt:158)
	at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:337)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.kt:427)
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.kt:320)
	at okhttp3.internal.http1.HeadersReader.readLine(HeadersReader.kt:29)
	at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:180)
	at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:110)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.kt:221)
	at org.snd.common.http.LoggingInterceptor.intercept(LoggingInterceptor.kt:20)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at org.snd.common.http.UserAgentInterceptor.intercept(UserAgentInterceptor.kt:10)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at org.snd.common.http.KavitaBearerAuthInterceptor.intercept(KavitaBearerAuthInterceptor.kt:12)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
	at org.snd.common.http.HttpClient$execute$1.invoke(HttpClient.kt:27)
	at org.snd.common.http.HttpClient$execute$1.invoke(HttpClient.kt:26)
	at org.snd.common.http.HttpClient.rateLimited$lambda$0(HttpClient.kt:54)
	at io.github.resilience4j.ratelimiter.RateLimiter.lambda$decorateCheckedSupplier$3(RateLimiter.java:219)
	at io.github.resilience4j.retry.Retry.lambda$decorateCheckedSupplier$1(Retry.java:135)
	at org.snd.common.http.HttpClient.rateLimited(HttpClient.kt:56)
	at org.snd.common.http.HttpClient.execute(HttpClient.kt:26)
	at org.snd.mediaserver.kavita.KavitaClient.updateSeriesMetadata(KavitaClient.kt:107)
	at org.snd.mediaserver.kavita.KavitaMediaServerClientAdapter.updateSeriesMetadata-mxbjABM(KavitaMediaServerClientAdapter.kt:106)
	at org.snd.mediaserver.MetadataUpdateService.updateSeriesMetadata(MetadataUpdateService.kt:63)
	at org.snd.mediaserver.MetadataUpdateService.updateMetadata(MetadataUpdateService.kt:50)
	at org.snd.mediaserver.MetadataService.matchSeriesMetadata-APDQdY8(MetadataService.kt:147)
	at org.snd.mediaserver.kavita.KavitaEventListener.processEvents(KavitaEventListener.kt:127)
	at org.snd.mediaserver.kavita.KavitaEventListener.processNotification$lambda$4(KavitaEventListener.kt:94)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.net.SocketException: Socket closed
	at java.base/sun.nio.ch.NioSocketImpl.endRead(Unknown Source)
	at java.base/sun.nio.ch.NioSocketImpl.implRead(Unknown Source)
	at java.base/sun.nio.ch.NioSocketImpl.read(Unknown Source)
	at java.base/sun.nio.ch.NioSocketImpl$1.read(Unknown Source)
	at java.base/java.net.Socket$SocketInputStream.read(Unknown Source)
	at okio.InputStreamSource.read(JvmOkio.kt:94)
	at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:125)
```

**Comment by DieselTech** [comment]
I don't know if it's edge cases with the few series I tried adding lately, but even when scanning 1 series in I'm seeing the CPU load spike to max (400% - 4 cores) in kavita now. Before the past update a single series would usually only use 60%-100% at most.

![image](https://github.com/Snd-R/komf/assets/30128380/997a4c00-631f-4e03-a69a-3d823134abd6)

**Comment by majora2007** [comment]
I made an update for the v0.7.11 release. I noticed that the API was fetching all people/tags/genres/etc to do the update, whereas it wasn't required. This should resolve this feature or at least scale down the issue drastically. 

https://github.com/Kareadita/Kavita/issues/2247

**Comment by DieselTech** [comment]
After having used said update referenced above ^ I haven't had the issues that were present in the past. I'm going to close this issue out for now. If it comes back up down the line I'll reopen.
