### ISSUE TITLE
Error code 500 after manually matching "To Love-Ru", changes don't apply in kavita

### ISSUE THREAD

**Issue by GlassedSilver** [Snd-R/komf#98]
My other manga work just fine. Komf and Kavita are both connected just fine and other manga identify and get edited through the user script.

```
09/19/2023 11:37:51 PM
23:37:51.999 [JettyServerThreadPool-61] INFO org.snd.mediaserver.MetadataUpdateService -- updating series To Love-Ru
09/19/2023 11:37:53 PM
23:37:53.392 [JettyServerThreadPool-61] WARN io.javalin.Javalin -- Uncaught exception
09/19/2023 11:37:53 PM
org.snd.common.exceptions.HttpException: response code: 400 url: http://kavita:5000/api/series/metadata body: Could not update metadata
09/19/2023 11:37:53 PM
	at org.snd.common.http.HttpClient.throwException(HttpClient.kt:69)
09/19/2023 11:37:53 PM
	at org.snd.common.http.HttpClient.access$throwException(HttpClient.kt:16)
09/19/2023 11:37:53 PM
	at org.snd.common.http.HttpClient$execute$1.invoke(HttpClient.kt:28)
09/19/2023 11:37:53 PM
	at org.snd.common.http.HttpClient$execute$1.invoke(HttpClient.kt:26)
09/19/2023 11:37:53 PM
	at org.snd.common.http.HttpClient.rateLimited$lambda$0(HttpClient.kt:54)
09/19/2023 11:37:53 PM
	at io.github.resilience4j.ratelimiter.RateLimiter.lambda$decorateCheckedSupplier$3(RateLimiter.java:219)
09/19/2023 11:37:53 PM
	at io.github.resilience4j.retry.Retry.lambda$decorateCheckedSupplier$1(Retry.java:135)
09/19/2023 11:37:53 PM
	at org.snd.common.http.HttpClient.rateLimited(HttpClient.kt:56)
09/19/2023 11:37:53 PM
	at org.snd.common.http.HttpClient.execute(HttpClient.kt:26)
09/19/2023 11:37:53 PM
	at org.snd.mediaserver.kavita.KavitaClient.updateSeriesMetadata(KavitaClient.kt:107)
09/19/2023 11:37:53 PM
	at org.snd.mediaserver.kavita.KavitaMediaServerClientAdapter.updateSeriesMetadata-mxbjABM(KavitaMediaServerClientAdapter.kt:106)
09/19/2023 11:37:53 PM
	at org.snd.mediaserver.MetadataUpdateService.updateSeriesMetadata(MetadataUpdateService.kt:63)
09/19/2023 11:37:53 PM
	at org.snd.mediaserver.MetadataUpdateService.updateMetadata(MetadataUpdateService.kt:50)
09/19/2023 11:37:53 PM
	at org.snd.mediaserver.MetadataService.setSeriesMetadata-_O6TCEk(MetadataService.kt:86)
09/19/2023 11:37:53 PM
	at org.snd.api.MetadataController.identifySeries(MetadataController.kt:92)
09/19/2023 11:37:53 PM
	at org.snd.api.MetadataController.register$lambda$1$lambda$0$identifySeries(MetadataController.kt:44)
09/19/2023 11:37:53 PM
	at io.javalin.routing.HandlerEntry.handle(HandlerEntry.kt:19)
09/19/2023 11:37:53 PM
	at io.javalin.http.servlet.DefaultTasks.HTTP$lambda$8$lambda$6$lambda$5(DefaultTasks.kt:39)
09/19/2023 11:37:53 PM
	at io.javalin.http.servlet.JavalinServlet.handleTask(JavalinServlet.kt:88)
09/19/2023 11:37:53 PM
	at io.javalin.http.servlet.JavalinServlet.handleSync(JavalinServlet.kt:53)
09/19/2023 11:37:53 PM
	at io.javalin.http.servlet.JavalinServlet.service(JavalinServlet.kt:41)
09/19/2023 11:37:53 PM
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:587)
09/19/2023 11:37:53 PM
	at io.javalin.jetty.JavalinJettyServlet.service(JavalinJettyServlet.kt:58)
09/19/2023 11:37:53 PM
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:587)
09/19/2023 11:37:53 PM
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:764)
09/19/2023 11:37:53 PM
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:529)
09/19/2023 11:37:53 PM
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)
09/19/2023 11:37:53 PM
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1570)
09/19/2023 11:37:53 PM
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)
09/19/2023 11:37:53 PM
	at io.javalin.jetty.JettyServer$start$wsAndHttpHandler$1.doHandle(JettyServer.kt:61)
09/19/2023 11:37:53 PM
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176)
09/19/2023 11:37:53 PM
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:484)
09/19/2023 11:37:53 PM
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1543)
09/19/2023 11:37:53 PM
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174)
09/19/2023 11:37:53 PM
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1303)
09/19/2023 11:37:53 PM
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129)
09/19/2023 11:37:53 PM
	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:173)
09/19/2023 11:37:53 PM
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
09/19/2023 11:37:53 PM
	at org.eclipse.jetty.server.Server.handle(Server.java:563)
09/19/2023 11:37:53 PM
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$0(HttpChannel.java:505)
09/19/2023 11:37:53 PM
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:762)
09/19/2023 11:37:53 PM
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:497)
09/19/2023 11:37:53 PM
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:282)
09/19/2023 11:37:53 PM
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)
09/19/2023 11:37:53 PM
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
09/19/2023 11:37:53 PM
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
09/19/2023 11:37:53 PM
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:416)
09/19/2023 11:37:53 PM
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:385)
09/19/2023 11:37:53 PM
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:272)
09/19/2023 11:37:53 PM
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.lambda$new$0(AdaptiveExecutionStrategy.java:140)
09/19/2023 11:37:53 PM
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411)
09/19/2023 11:37:53 PM
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)
09/19/2023 11:37:53 PM
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)
09/19/2023 11:37:53 PM
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)
09/19/2023 11:37:53 PM
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by Snd-R** [comment]
Do you have merge tags and genres option enabled? If there are two similar looking tags aggregated from multiple sources Kavita will normalize them to the same tag and will fail with similar error

**Comment by GlassedSilver** [comment]
Yeah I have merge tags enabled. So it seems Kavita should stop erroring out on adding dupe tags then huh?

**Comment by Snd-R** [comment]
It should be fixed in the latest version

**Comment by GlassedSilver** [comment]
Thank you so much! Can confirm it's working!
